table ExchangeRates
	lineageTag: 97443b1d-382e-4d8e-a6e8-526c8068417b

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5bd033c4-e594-4230-a2d2-44283030a30a
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FromCurrency
		dataType: string
		lineageTag: e193ed6c-c9f2-40f4-a52e-e39fb84124c3
		summarizeBy: none
		sourceColumn: FromCurrency

		annotation SummarizationSetBy = Automatic

	column ToCurrency
		dataType: string
		lineageTag: c484ce83-c05e-4595-8b9f-c5b1b9ad26ce
		summarizeBy: none
		sourceColumn: ToCurrency

		annotation SummarizationSetBy = Automatic

	column Rate
		dataType: double
		lineageTag: 4b605f58-5ca7-4db7-aec9-758d1d7996bd
		summarizeBy: sum
		sourceColumn: Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ExchangeRates = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "exchange_rates" ),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders,{{"Date", type date}, {"FromCurrency", type text}, {"ToCurrency", type text}, {"Rate", type number}})
				in
				    ChangedType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

