table Geography
	lineageTag: e1efdba3-1f8e-4419-a2cc-15ee8ccae934

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: b6c43b13-0208-43d9-849c-703285b7fe7d
		summarizeBy: count
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: dc69bb8a-690d-4e9a-b19c-5af57549fc39
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 894c16d4-2c79-4475-9d53-01cd2e5c9da4
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 4bc0780d-695c-4c3a-ab2a-e1e4a5b6310a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: string
		lineageTag: f536c8db-4899-43c1-84c7-992733e0937d
		summarizeBy: none
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

	partition Geography = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "geography" ),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders,{{"GeographyKey", Int64.Type}, {"City", type text}, {"State", type text}, {"Country", type text}, {"Continent", type text}, {"ISOCode", type text}}),
				    RemovedColumns = Table.RemoveColumns(ChangedType,{"ISOCode"})
				in
				    RemovedColumns

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

