changelog:
  categories:
    - title: Features
      labels: ["feature", "enhancement", "feat", "chore"]
    - title: Fixes
      labels: ["bug", "fix"]
    - title: Refactors / Performance
      labels: ["refactor", "performance", "refac", "perf"]
    - title: Docs
      labels: ["docs"]
    - title: Other
      labels: ["*"]
  exclude:
    labels: ["ignore-for-release"]
