createOrReplace

	ref table MeasuresTable

		measure '# Customers' =
				
				DISTINCTCOUNT ( SalesOrderHeader[CustomerKey] )
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: 6ec8f0ae-723d-46cd-b46d-b9c1cedc3068

			changedProperty = IsHidden

		measure 'Cost Amount' = ```
				
				SUMX ( 
				    SalesOrderDetail, 
				    SalesOrderDetail[Quantity] * SalesOrderDetail[UnitCost]
				)
				```
			formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
			displayFolder: 01 - Base Measures
			lineageTag: 161627e6-1af2-4474-94e3-8f71733d228e

			changedProperty = IsHidden

			annotation PBI_FormatHint = {"currencyCulture":"en-US"}

		measure 'Employee Sales by Store Assgn.' = ```
				
				CALCULATE ( 
				    [Sales Amount (SOD)],
				    TREATAS ( 
				        GENERATE ( 
				            SUMMARIZE ( 
				                EmployeeStoreAssignment, 
				                EmployeeStoreAssignment[StoreKey],
				                Employee[EmployeeKey]
				            ),
				            DATESBETWEEN ( 
				                Dates[Date],
				                CALCULATE ( MIN ( EmployeeStoreAssignment[StartDate] ) ),
				                CALCULATE ( MAX ( EmployeeStoreAssignment[EndDate] ) )
				            )
				        ),
				        SalesOrderHeader[StoreKey],
				        SalesOrderHeader[SalesPersonEmployeeKey],
				        Dates[Date]
				    )
				)
				```
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: 6e2a3e49-3874-454d-9900-6ed7240870fe

			annotation PBI_FormatHint = {"isDecimal":true}

		measure 'Profit Amount' =
				
				[Sales Amount] - [Cost Amount]
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: a95a2156-9a97-45f8-b9a9-08a4ef5a8d06

			changedProperty = IsHidden

			annotation PBI_FormatHint = {"isDecimal":true}

		measure 'Sales Amount' = ```
				
				SUMX ( 
				    SalesOrderDetail, 
				    SalesOrderDetail[Quantity] * SalesOrderDetail[NetPrice]
				)
				```
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: 48d9e8b9-f997-475d-b363-973edb1d5bb3

			changedProperty = IsHidden

			annotation PBI_FormatHint = {"isDecimal":true}

		measure 'Sales Amount (SOD)' = ```
				
				SUMX ( 
				    SalesOrderDetail, 
				    SalesOrderDetail[Quantity] * SalesOrderDetail[NetPrice]
				)
				```
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: 6e07a49f-8504-460e-9f2c-9364cd1dbd89

			changedProperty = IsHidden

			annotation PBI_FormatHint = {"isDecimal":true}

		measure Transactions =
				
				COUNTROWS ( SalesOrderDetail )
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: f941d2a9-2c52-4441-ba75-afa6c2f91413

			changedProperty = IsHidden

