table Employee
	lineageTag: 5468535c-f52b-404e-b6ac-ec17b52a274a

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 8a8ff06e-f2ec-4cd3-b652-bc238a544935
		summarizeBy: count
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = Automatic

	column ParentEmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: b41d2132-1d3d-4cc2-9269-e77ec31a774e
		summarizeBy: count
		sourceColumn: ParentEmployeeKey

		annotation SummarizationSetBy = Automatic

	column EmployeeName
		dataType: string
		lineageTag: 9cc74c33-ab59-49dc-adbc-acb5e420a25c
		summarizeBy: none
		sourceColumn: EmployeeName

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 1cdffb64-a4c7-4d51-8286-58e9139dee58
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column OrgLevel
		dataType: int64
		formatString: 0
		lineageTag: 417b30a2-403d-4726-8519-3420b6d046b3
		summarizeBy: sum
		sourceColumn: OrgLevel

		annotation SummarizationSetBy = Automatic

	column OrgUnitType
		dataType: string
		lineageTag: 74022302-f9a8-4d3f-aac5-fd3fc4008e64
		summarizeBy: none
		sourceColumn: OrgUnitType

		annotation SummarizationSetBy = Automatic

	column RegionId
		dataType: int64
		formatString: 0
		lineageTag: 39edb675-e033-4638-b300-76ca7556ba92
		summarizeBy: count
		sourceColumn: RegionId

		annotation SummarizationSetBy = Automatic

	column DistrictId
		dataType: int64
		formatString: 0
		lineageTag: 3c7ef738-e081-4ba2-8a8a-d753eedd20f0
		summarizeBy: count
		sourceColumn: DistrictId

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: d2c6eb98-c601-4edb-a72b-86a21fa153cb
		summarizeBy: count
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: 0e88fa78-511e-4d71-884b-f01ed78f69fc
		summarizeBy: count
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 52d94853-ce0d-4b8d-9d2f-15eee8fe715d
		summarizeBy: none
		sourceColumn: HireDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column TerminationDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 30004b5d-6725-4689-8e8a-ac153fc12565
		summarizeBy: none
		sourceColumn: TerminationDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column TerminationReason
		dataType: string
		lineageTag: 5b87612e-0400-4cb2-9d39-e0e9d5c8af55
		summarizeBy: none
		sourceColumn: TerminationReason

		annotation SummarizationSetBy = Automatic

	column IsActive
		dataType: int64
		formatString: 0
		lineageTag: 06130675-3a9d-482f-b5e8-90b9350e327b
		summarizeBy: sum
		sourceColumn: IsActive

		annotation SummarizationSetBy = Automatic

	column EmploymentType
		dataType: string
		lineageTag: 24820415-445d-41e4-94bd-3340cdf537de
		summarizeBy: none
		sourceColumn: EmploymentType

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: 299edc0a-7afe-4bbf-b276-0a55556c8d18
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gender
		dataType: string
		lineageTag: 1744009b-f7e4-4815-8c26-417f7e6c0f34
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: be7d5e46-3041-49b7-89bb-91e29e436998
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 6f844891-45eb-45d0-a4f6-71a9c5a50759
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column MiddleName
		dataType: string
		lineageTag: 835ec944-949c-41ce-bd64-e552d400d6f1
		summarizeBy: none
		sourceColumn: MiddleName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 863c05e1-1b3d-429f-9303-646cbe96f11f
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column MaritalStatus
		dataType: string
		lineageTag: 072c1ff2-a983-4168-b942-4c9ed61097df
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 9520a975-18ba-4731-bac6-f84532131738
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: d6bbcdbb-01be-456a-ac3d-fc8c96d4b37f
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column EmergencyContactName
		dataType: string
		lineageTag: b0c5f44c-fa67-4763-b3ee-ebbf04f6390b
		summarizeBy: none
		sourceColumn: EmergencyContactName

		annotation SummarizationSetBy = Automatic

	column EmergencyContactPhone
		dataType: string
		lineageTag: ec77419d-f43c-4fcc-b275-0c88c4dfecd2
		summarizeBy: none
		sourceColumn: EmergencyContactPhone

		annotation SummarizationSetBy = Automatic

	column SalariedFlag
		dataType: int64
		formatString: 0
		lineageTag: 0943fee2-3942-454b-8fc7-05aaec31baca
		summarizeBy: sum
		sourceColumn: SalariedFlag

		annotation SummarizationSetBy = Automatic

	column PayFrequency
		dataType: int64
		formatString: 0
		lineageTag: 65b3d041-79f2-43b3-ade7-f7b6e64f51cd
		summarizeBy: sum
		sourceColumn: PayFrequency

		annotation SummarizationSetBy = Automatic

	column BaseRate
		dataType: double
		lineageTag: 7aed36e9-5069-448e-8886-e6a33f27b433
		summarizeBy: sum
		sourceColumn: BaseRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VacationHours
		dataType: int64
		formatString: 0
		lineageTag: 0f60d53e-0152-41ca-9f82-74e5b7bc7afa
		summarizeBy: sum
		sourceColumn: VacationHours

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: bc741ace-458a-4105-b0d1-a543bcae6830
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column SalesPersonFlag
		dataType: int64
		formatString: 0
		lineageTag: b3ec8d5a-7747-46f7-bb4f-5d70876d6093
		summarizeBy: sum
		sourceColumn: SalesPersonFlag

		annotation SummarizationSetBy = Automatic

	column DepartmentName
		dataType: string
		lineageTag: 7ba0dd8e-529a-4e19-bf51-a6dc19807a7f
		summarizeBy: none
		sourceColumn: DepartmentName

		annotation SummarizationSetBy = Automatic

	partition Employee = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source      = FxReadParquetFile ( "dimensions\employees" ),
				    ChangedType = Table.TransformColumnTypes ( Source, { { "ParentEmployeeKey", Int64.Type } } )
				in
				    ChangedType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

