table MeasureTable
	lineageTag: 0585b77d-b129-4c0e-9763-a29089eabcd3

	measure 'Profit Amount' =
			
			[Sales Amount] - [Cost Amount]
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: a95a2156-9a97-45f8-b9a9-08a4ef5a8d06

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Transactions =
			
			COUNTROWS ( Sales )
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: f941d2a9-2c52-4441-ba75-afa6c2f91413

	measure 'Sales Amount' = ```
			
			SUMX ( 
			    Sales,
			    Sales[Quantity] * Sales[NetPrice]
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 0d511203-d4fa-4fbf-bed4-84ce7a184526

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '# Customers' =
			
			DISTINCTCOUNT ( Sales[CustomerKey] )
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 174e935b-1f31-468a-b9a3-8e4c43aa2487

	measure 'Cost Amount' = ```
			
			SUMX ( 
			    Sales, 
			    Sales[Quantity] * Sales[UnitCost]
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 316bc9a9-7992-4938-830c-767ce80a76be

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Employee Sales by Store Assgn.' = ```
			
			CALCULATE ( 
			    [Sales Amount],
			    TREATAS ( 
			        GENERATE ( 
			            SUMMARIZE ( 
			                EmployeeStoreAssignment, 
			                EmployeeStoreAssignment[StoreKey],
			                Employee[EmployeeKey]
			            ),
			            DATESBETWEEN ( 
			                Dates[Date],
			                CALCULATE ( MIN ( EmployeeStoreAssignment[StartDate] ) ),
			                CALCULATE ( MAX ( EmployeeStoreAssignment[EndDate] ) )
			            )
			        ),
			        Sales[StoreKey],
			        Sales[SalesPersonEmployeeKey],
			        Dates[Date]
			    )
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 9ea4b942-f332-4920-b527-413f495e5a02

		annotation PBI_FormatHint = {"isDecimal":true}

	column Column1
		dataType: string
		isHidden
		lineageTag: edd2d66e-98a3-429e-8dc6-c41e7d5a3847
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition MeasureTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

