table SalesChannel
	lineageTag: 58345d4a-ca8f-4681-a02c-ddf07824b262

	column SalesChannelKey
		dataType: int64
		formatString: 0
		lineageTag: 7fa10691-46f2-4382-badb-a7f8ba6d81e2
		summarizeBy: count
		sourceColumn: SalesChannelKey

		annotation SummarizationSetBy = Automatic

	column SalesChannel
		dataType: string
		lineageTag: 09c6eb7e-015f-4741-ab4a-87d0f3303f56
		summarizeBy: none
		sourceColumn: SalesChannel

		annotation SummarizationSetBy = Automatic

	column SalesChannelDescription
		dataType: string
		lineageTag: 9ec33bc8-a141-4fcd-82c6-3877146ced6c
		summarizeBy: none
		sourceColumn: SalesChannelDescription

		annotation SummarizationSetBy = Automatic

	column ChannelGroup
		dataType: string
		lineageTag: d3f6b063-8e5d-4d69-b7f9-0aa1368abc42
		summarizeBy: none
		sourceColumn: ChannelGroup

		annotation SummarizationSetBy = Automatic

	column ChannelGroupDescription
		dataType: string
		lineageTag: 3b79f79d-dd1d-4b5c-8444-67e948a04e0b
		summarizeBy: none
		sourceColumn: ChannelGroupDescription

		annotation SummarizationSetBy = Automatic

	column SalesChannelCode
		dataType: string
		lineageTag: 7779561a-d3d1-4bde-a5ea-bfa1c56d23f6
		summarizeBy: none
		sourceColumn: SalesChannelCode

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: c38a78ee-e00c-4f5b-a6e3-afcd7f9997b3
		summarizeBy: sum
		sourceColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	column IsDigital
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 48fb3608-cbcb-49c6-a429-1e7348b1f146
		summarizeBy: none
		sourceColumn: IsDigital

		annotation SummarizationSetBy = Automatic

	column IsPhysical
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: efe98a8f-647f-4342-b390-d58551f76470
		summarizeBy: none
		sourceColumn: IsPhysical

		annotation SummarizationSetBy = Automatic

	column IsThirdParty
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 19c195f8-cca0-418a-a870-5c5244cf6d4d
		summarizeBy: none
		sourceColumn: IsThirdParty

		annotation SummarizationSetBy = Automatic

	column IsB2B
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a81534bb-f960-4075-80a7-2b252936f279
		summarizeBy: none
		sourceColumn: IsB2B

		annotation SummarizationSetBy = Automatic

	column IsAssisted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b54fcc26-7ea4-425e-8018-af1cb9924992
		summarizeBy: none
		sourceColumn: IsAssisted

		annotation SummarizationSetBy = Automatic

	column IsOwnedChannel
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 43a16a1a-45dd-4815-bdbe-0f1405b0b23c
		summarizeBy: none
		sourceColumn: IsOwnedChannel

		annotation SummarizationSetBy = Automatic

	column Is24x7
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 36c67edb-5f85-4a02-bd10-6420273b0966
		summarizeBy: none
		sourceColumn: Is24x7

		annotation SummarizationSetBy = Automatic

	column OpenTime
		dataType: string
		lineageTag: 797f21fa-722f-4153-8988-ad0fbc45dd69
		summarizeBy: none
		sourceColumn: OpenTime

		annotation SummarizationSetBy = Automatic

	column CloseTime
		dataType: string
		lineageTag: d7302ce4-4a5d-45c0-8797-70d2f90be576
		summarizeBy: none
		sourceColumn: CloseTime

		annotation SummarizationSetBy = Automatic

	column CommissionRate
		dataType: double
		lineageTag: 967dff71-12dd-48c1-a019-67310deb335c
		summarizeBy: sum
		sourceColumn: CommissionRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TypicalFulfillmentDays
		dataType: int64
		formatString: 0
		lineageTag: 7002e91f-eb71-46f7-a446-32a9ef750207
		summarizeBy: sum
		sourceColumn: TypicalFulfillmentDays

		annotation SummarizationSetBy = Automatic

	partition SalesChannel = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source     = FxReadParquetFile ( "dimensions\sales_channels" ),
				    ChangeType = Table.TransformColumnTypes ( Source, { { "SalesChannelKey", Int64.Type } } )
				in
				    ChangeType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

