table Currency
	lineageTag: 6abe0bfa-86b5-4aa4-b99e-18a7cdc2214d

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 05d148a7-8f50-4672-af86-2acd1915bde8
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column CurrencyName
		dataType: string
		lineageTag: 6a1b6312-51a5-48d6-8ce5-01e59ef35ba2
		summarizeBy: none
		sourceColumn: CurrencyName

		annotation SummarizationSetBy = Automatic

	column CurrencyCode
		dataType: string
		lineageTag: 3baa434f-4bcf-479e-b4c9-71a7826560e6
		summarizeBy: none
		sourceColumn: CurrencyCode

		annotation SummarizationSetBy = Automatic

	column CurrencySymbol
		dataType: string
		lineageTag: 5d098d43-ad91-40b2-a6a0-eec02c11a0ac
		summarizeBy: none
		sourceColumn: CurrencySymbol

		annotation SummarizationSetBy = Automatic

	column DecimalPlaces
		dataType: int64
		formatString: 0
		lineageTag: 7ff1b987-1597-4011-b1af-9dba09de7844
		summarizeBy: sum
		sourceColumn: DecimalPlaces

		annotation SummarizationSetBy = Automatic

	partition Currency = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source          = FxReadCSVFile ( "dimensions", "currency" ),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"CurrencyKey", Int64.Type}, {"CurrencyCode", type text}, {"CurrencyName", type text}, {"CurrencySymbol", type text}, {"DecimalPlaces", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

