table Currency
	lineageTag: 6abe0bfa-86b5-4aa4-b99e-18a7cdc2214d

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 05d148a7-8f50-4672-af86-2acd1915bde8
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column CurrencyName
		dataType: string
		lineageTag: 6a1b6312-51a5-48d6-8ce5-01e59ef35ba2
		summarizeBy: none
		sourceColumn: CurrencyName

		annotation SummarizationSetBy = Automatic

	column ToCurrency
		dataType: string
		lineageTag: b5b079c9-2563-4898-916f-56bfef58d097
		summarizeBy: none
		sourceColumn: ToCurrency

		annotation SummarizationSetBy = Automatic

	partition Currency = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source      = FxReadCSVFile ( "dimensions", "currency" ),
				    ChangedType = Table.TransformColumnTypes ( Source, { { "CurrencyKey", Int64.Type } } )
				in
				    ChangedType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

