table Dates
	lineageTag: 1e93e289-4d40-485f-9fbc-7760c3c5e1fd
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 3fd4def5-f7ac-43bb-b84a-3bab249d71e1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 39c1bef1-cb8a-4c3f-8251-70835117b54d
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 996eb0fd-712d-4c55-b1e1-c3fb6938ba86
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column IsYearStart
		dataType: int64
		formatString: 0
		lineageTag: 0fa01c5a-256d-4a9b-8846-df82a8e04316
		summarizeBy: sum
		sourceColumn: IsYearStart

		annotation SummarizationSetBy = Automatic

	column IsYearEnd
		dataType: int64
		formatString: 0
		lineageTag: e01fa196-d101-42f9-8ed9-a96013bf317d
		summarizeBy: sum
		sourceColumn: IsYearEnd

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 45ccab9c-ce97-43bf-8e64-e11a01b2663d
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterStartDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: c461ebcb-c06a-4fef-916a-e5bcb1fb8584
		summarizeBy: none
		sourceColumn: QuarterStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QuarterEndDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: dc499a69-273c-4b3b-a9b8-b0ba8bb8a289
		summarizeBy: none
		sourceColumn: QuarterEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsQuarterStart
		dataType: int64
		formatString: 0
		lineageTag: ccb9f3a0-81eb-4680-8416-4336a5807833
		summarizeBy: sum
		sourceColumn: IsQuarterStart

		annotation SummarizationSetBy = Automatic

	column IsQuarterEnd
		dataType: int64
		formatString: 0
		lineageTag: e42a4d4e-1e5a-46b3-98c2-594bc49b72f2
		summarizeBy: sum
		sourceColumn: IsQuarterEnd

		annotation SummarizationSetBy = Automatic

	column QuarterYear
		dataType: string
		lineageTag: 99dacc30-46c9-41cd-b8bc-02a7917d57b0
		summarizeBy: none
		sourceColumn: QuarterYear

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 5de2751c-c920-47e7-ad61-50362f65a8dd
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1c1b18b8-f048-48be-8ea1-4b1b458d11b5
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: 629c62a1-d4cf-47d5-ba88-01888209e775
		summarizeBy: none
		sourceColumn: MonthShort

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: e1d2c99f-5076-4a6a-b114-ea862dbd50c8
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthEndDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2453504c-d732-4600-a8e4-0519ce4281a9
		summarizeBy: none
		sourceColumn: MonthEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: dec1a8fb-1746-4776-8c7c-5e32a44bd907
		summarizeBy: none
		sourceColumn: MonthYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthYearNumber
		dataType: int64
		formatString: 0
		lineageTag: c2d4c82e-8707-4d57-8ddb-8f87e1074676
		summarizeBy: sum
		sourceColumn: MonthYearNumber

		annotation SummarizationSetBy = Automatic

	column CalendarMonthIndex
		dataType: int64
		formatString: 0
		lineageTag: 3a2407da-1f0a-490a-b6ec-cfa0af5c409d
		summarizeBy: sum
		sourceColumn: CalendarMonthIndex

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterIndex
		dataType: int64
		formatString: 0
		lineageTag: 569a30fa-6067-48fd-954c-2c2aa675e9e2
		summarizeBy: sum
		sourceColumn: CalendarQuarterIndex

		annotation SummarizationSetBy = Automatic

	column IsMonthStart
		dataType: int64
		formatString: 0
		lineageTag: 7ba9a583-cc65-49c4-bfae-4ef5cabe119d
		summarizeBy: sum
		sourceColumn: IsMonthStart

		annotation SummarizationSetBy = Automatic

	column IsMonthEnd
		dataType: int64
		formatString: 0
		lineageTag: c296b142-d065-41b6-be89-9b0ab2f75b51
		summarizeBy: sum
		sourceColumn: IsMonthEnd

		annotation SummarizationSetBy = Automatic

	column WeekOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 5427df1a-095d-45a6-b3a1-96273463af73
		summarizeBy: sum
		sourceColumn: WeekOfMonth

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 1a997df4-2abb-4de1-8d9d-8305dbd43ed1
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 79ec9d90-0bf8-455b-b330-6d5ef21a0ed3
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: efe73c27-c199-4ae3-b85c-e610acda1698
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column DayOfYear
		dataType: int64
		formatString: 0
		lineageTag: 1a8fe719-2776-4cef-8344-f4251db4e5fa
		summarizeBy: sum
		sourceColumn: DayOfYear

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 7d6e8180-ddfd-4ad8-bdb6-1f43015c81b3
		summarizeBy: sum
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: int64
		formatString: 0
		lineageTag: 4d167d05-7c47-44dd-bf28-0da4c96613b6
		summarizeBy: sum
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsBusinessDay
		dataType: int64
		formatString: 0
		lineageTag: 1f5ca372-3aa6-4b9a-b2a9-fb547bd03381
		summarizeBy: sum
		sourceColumn: IsBusinessDay

		annotation SummarizationSetBy = Automatic

	column NextBusinessDay
		dataType: dateTime
		formatString: Short Date
		lineageTag: 05d82fbc-a2c9-49a1-ac20-9079af2e0bc7
		summarizeBy: none
		sourceColumn: NextBusinessDay

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PreviousBusinessDay
		dataType: dateTime
		formatString: Short Date
		lineageTag: e3c83809-8168-44ff-8169-b9c8dd4e84f9
		summarizeBy: none
		sourceColumn: PreviousBusinessDay

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsToday
		dataType: int64
		formatString: 0
		lineageTag: 98462bd4-960c-46d6-8406-bf743cef09f9
		summarizeBy: sum
		sourceColumn: IsToday

		annotation SummarizationSetBy = Automatic

	column IsCurrentYear
		dataType: int64
		formatString: 0
		lineageTag: c2cba7b4-0a8f-47e5-a4dd-4c8e3c651b4b
		summarizeBy: sum
		sourceColumn: IsCurrentYear

		annotation SummarizationSetBy = Automatic

	column IsCurrentMonth
		dataType: int64
		formatString: 0
		lineageTag: 84c60459-6920-4c6a-aa08-c727841407ba
		summarizeBy: sum
		sourceColumn: IsCurrentMonth

		annotation SummarizationSetBy = Automatic

	column IsCurrentQuarter
		dataType: int64
		formatString: 0
		lineageTag: 4323b79a-710a-437c-a338-72047e9d261a
		summarizeBy: sum
		sourceColumn: IsCurrentQuarter

		annotation SummarizationSetBy = Automatic

	column CurrentDayOffset
		dataType: int64
		formatString: 0
		lineageTag: 59701842-1673-4a62-9f00-2dc46610c9d6
		summarizeBy: sum
		sourceColumn: CurrentDayOffset

		annotation SummarizationSetBy = Automatic

	column SequentialDayIndex
		dataType: string
		lineageTag: 1984f18e-ea30-4944-b91f-8447d3a4b36d
		summarizeBy: none
		sourceColumn: SequentialDayIndex

		annotation SummarizationSetBy = Automatic

	column MonthNameShort
		dataType: string
		lineageTag: 7c08252c-c3a4-450a-97a3-71fd2b54a55a
		summarizeBy: none
		sourceColumn: MonthNameShort

		annotation SummarizationSetBy = Automatic

	column YearMonthKey
		dataType: string
		lineageTag: f8107182-0c89-48a3-8240-d37d7c12188b
		summarizeBy: none
		sourceColumn: YearMonthKey

		annotation SummarizationSetBy = Automatic

	column YearMonthLabel
		dataType: string
		lineageTag: e8c674e1-0971-44d3-a4fb-dda752a734b5
		summarizeBy: none
		sourceColumn: YearMonthLabel

		annotation SummarizationSetBy = Automatic

	column YearQuarterKey
		dataType: string
		lineageTag: 229756f1-1e09-4925-ad09-686b3f9a88a9
		summarizeBy: none
		sourceColumn: YearQuarterKey

		annotation SummarizationSetBy = Automatic

	column YearQuarterLabel
		dataType: string
		lineageTag: 321a0c81-a6ed-427a-91f2-4506177bdc5d
		summarizeBy: none
		sourceColumn: YearQuarterLabel

		annotation SummarizationSetBy = Automatic

	column DayNameShort
		dataType: string
		lineageTag: c1aad88f-1e09-4c13-aac4-4920dde68805
		summarizeBy: none
		sourceColumn: DayNameShort

		annotation SummarizationSetBy = Automatic

	column YearOffset
		dataType: string
		lineageTag: e87dd29e-2a18-461f-a87c-7dc332cd38a1
		summarizeBy: none
		sourceColumn: YearOffset

		annotation SummarizationSetBy = Automatic

	column CalendarMonthOffset
		dataType: string
		lineageTag: 3332278c-b968-4f43-8187-58f8cf7b1da1
		summarizeBy: none
		sourceColumn: CalendarMonthOffset

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterOffset
		dataType: string
		lineageTag: 922cacf6-a73b-40f5-bd1b-02366ffb5469
		summarizeBy: none
		sourceColumn: CalendarQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FiscalYearStartYear
		dataType: string
		lineageTag: cb08f607-3432-4ee5-be23-792c7d2f9f04
		summarizeBy: none
		sourceColumn: FiscalYearStartYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNumber
		dataType: string
		lineageTag: 4cdd2ac4-b214-4b0b-9fa2-594de17d1dd9
		summarizeBy: none
		sourceColumn: FiscalMonthNumber

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterNumber
		dataType: string
		lineageTag: d70348d8-d68d-43ee-810f-bba692a24984
		summarizeBy: none
		sourceColumn: FiscalQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FiscalMonthIndex
		dataType: string
		lineageTag: 6f349c61-fe52-412b-a29a-5eb0ce200ac3
		summarizeBy: none
		sourceColumn: FiscalMonthIndex

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterIndex
		dataType: string
		lineageTag: 7608d371-fecc-4c87-bdc9-927d03da3be7
		summarizeBy: none
		sourceColumn: FiscalQuarterIndex

		annotation SummarizationSetBy = Automatic

	column FiscalMonthOffset
		dataType: string
		lineageTag: 7060f37b-ec58-4f19-bc46-f9d80cf9a2ad
		summarizeBy: none
		sourceColumn: FiscalMonthOffset

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterOffset
		dataType: string
		lineageTag: 6c0089ec-7eb9-4a33-a9cf-310284edcfd6
		summarizeBy: none
		sourceColumn: FiscalQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterName
		dataType: string
		lineageTag: 04599292-ab16-4dcb-9da7-108703576164
		summarizeBy: none
		sourceColumn: FiscalQuarterName

		annotation SummarizationSetBy = Automatic

	column FiscalYearBin
		dataType: string
		lineageTag: b51e243d-c9f9-4b09-8c0b-0c40aa67c0b5
		summarizeBy: none
		sourceColumn: FiscalYearBin

		annotation SummarizationSetBy = Automatic

	column FiscalYearMonthNumber
		dataType: string
		lineageTag: b5dca94e-043e-449f-9039-fe7a9fd28b89
		summarizeBy: none
		sourceColumn: FiscalYearMonthNumber

		annotation SummarizationSetBy = Automatic

	column FiscalYearQuarterNumber
		dataType: string
		lineageTag: b29c75b3-3fd8-4235-9c6a-ac88770224c1
		summarizeBy: none
		sourceColumn: FiscalYearQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FiscalYearStartDate
		dataType: string
		lineageTag: 6ca218b8-eb50-4d03-91ce-47662d981d1a
		summarizeBy: none
		sourceColumn: FiscalYearStartDate

		annotation SummarizationSetBy = Automatic

	column FiscalYearEndDate
		dataType: string
		lineageTag: 09deb1a3-d7a9-4f09-aa2d-bc8e3753973d
		summarizeBy: none
		sourceColumn: FiscalYearEndDate

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterStartDate
		dataType: string
		lineageTag: af7050f0-01f4-4bf9-a0b1-a633667e016f
		summarizeBy: none
		sourceColumn: FiscalQuarterStartDate

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterEndDate
		dataType: string
		lineageTag: 368849a8-b454-460d-bc7a-a3d354b5c04a
		summarizeBy: none
		sourceColumn: FiscalQuarterEndDate

		annotation SummarizationSetBy = Automatic

	column IsFiscalYearStart
		dataType: string
		lineageTag: 3a89ef55-e206-44f0-b0fa-839ca48b9935
		summarizeBy: none
		sourceColumn: IsFiscalYearStart

		annotation SummarizationSetBy = Automatic

	column IsFiscalYearEnd
		dataType: string
		lineageTag: c23cd28f-f60b-4210-ac8b-d15dedafd159
		summarizeBy: none
		sourceColumn: IsFiscalYearEnd

		annotation SummarizationSetBy = Automatic

	column IsFiscalQuarterStart
		dataType: string
		lineageTag: 9ba9da4a-b532-44a4-b9e3-e6f6e418c33d
		summarizeBy: none
		sourceColumn: IsFiscalQuarterStart

		annotation SummarizationSetBy = Automatic

	column IsFiscalQuarterEnd
		dataType: string
		lineageTag: 6728d07c-3cb1-4fe5-a2aa-dea04ed694c8
		summarizeBy: none
		sourceColumn: IsFiscalQuarterEnd

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: string
		lineageTag: bab07234-7fe0-4a91-8a06-3704b4f3ea08
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalYearLabel
		dataType: string
		lineageTag: c78a8a44-6a05-40d0-8a11-f38af327bbe6
		summarizeBy: none
		sourceColumn: FiscalYearLabel

		annotation SummarizationSetBy = Automatic

	column FiscalSystem
		dataType: string
		lineageTag: 69f75891-db2b-4f2b-a336-0f3cc361a57b
		summarizeBy: none
		sourceColumn: FiscalSystem

		annotation SummarizationSetBy = Automatic

	column WeeklyFiscalSystem
		dataType: string
		lineageTag: be77d6d9-4d4c-402e-afe5-be601b57d68c
		summarizeBy: none
		sourceColumn: WeeklyFiscalSystem

		annotation SummarizationSetBy = Automatic

	column FWYearNumber
		dataType: string
		lineageTag: b98fc654-0fe5-4059-a30a-36982c8a5644
		summarizeBy: none
		sourceColumn: FWYearNumber

		annotation SummarizationSetBy = Automatic

	column FWYearLabel
		dataType: string
		lineageTag: ba7d1cd4-e4fd-4431-a509-50b18c3e76f7
		summarizeBy: none
		sourceColumn: FWYearLabel

		annotation SummarizationSetBy = Automatic

	column FWQuarterNumber
		dataType: string
		lineageTag: 8d3a0b08-6173-4214-b450-0c3bcfb51012
		summarizeBy: none
		sourceColumn: FWQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWQuarterLabel
		dataType: string
		lineageTag: d8a3d3e4-7c63-47e1-83b4-d97b29b625d4
		summarizeBy: none
		sourceColumn: FWQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FWYearQuarterNumber
		dataType: string
		lineageTag: 83626894-76ca-4ec9-9807-118194bc2831
		summarizeBy: none
		sourceColumn: FWYearQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWYearQuarterOffset
		dataType: string
		lineageTag: 80511eae-5513-421e-a3b5-2981d0854ad2
		summarizeBy: none
		sourceColumn: FWYearQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FWMonthNumber
		dataType: string
		lineageTag: 71549ab9-7d0a-4486-8045-7107cf66781a
		summarizeBy: none
		sourceColumn: FWMonthNumber

		annotation SummarizationSetBy = Automatic

	column FWMonthLabel
		dataType: string
		lineageTag: 0e5c6f4c-bafa-495e-b19a-4a55b7407c34
		summarizeBy: none
		sourceColumn: FWMonthLabel

		annotation SummarizationSetBy = Automatic

	column FWYearMonthNumber
		dataType: string
		lineageTag: bc411fb8-4bb1-4f0e-bc8f-8eda44f1b373
		summarizeBy: none
		sourceColumn: FWYearMonthNumber

		annotation SummarizationSetBy = Automatic

	column FWYearMonthOffset
		dataType: string
		lineageTag: 1b28adcf-228a-4929-8f5f-c3be3157b47a
		summarizeBy: none
		sourceColumn: FWYearMonthOffset

		annotation SummarizationSetBy = Automatic

	column FWWeekNumber
		dataType: string
		lineageTag: 9ceaf5e7-f914-4cd0-9d60-b19cfda5911c
		summarizeBy: none
		sourceColumn: FWWeekNumber

		annotation SummarizationSetBy = Automatic

	column FWWeekLabel
		dataType: string
		lineageTag: 95a1acb2-d3ab-4938-ab61-96469716f63f
		summarizeBy: none
		sourceColumn: FWWeekLabel

		annotation SummarizationSetBy = Automatic

	column FWYearWeekNumber
		dataType: string
		lineageTag: b8f9e47f-57ab-46b8-b01f-652ed8cd8f48
		summarizeBy: none
		sourceColumn: FWYearWeekNumber

		annotation SummarizationSetBy = Automatic

	column FWYearWeekOffset
		dataType: string
		lineageTag: c6807633-8e42-4889-b7a7-2d2b3deeb3d3
		summarizeBy: none
		sourceColumn: FWYearWeekOffset

		annotation SummarizationSetBy = Automatic

	column FWYearWeekLabel
		dataType: string
		lineageTag: 6bc510a4-d4ec-4c71-96d5-207291726d23
		summarizeBy: none
		sourceColumn: FWYearWeekLabel

		annotation SummarizationSetBy = Automatic

	column FWPeriodNumber
		dataType: string
		lineageTag: f00920ac-616f-4761-966e-189f885ef963
		summarizeBy: none
		sourceColumn: FWPeriodNumber

		annotation SummarizationSetBy = Automatic

	column FWPeriodLabel
		dataType: string
		lineageTag: d55c7ffe-f61e-4bca-880b-ab7a8da428d2
		summarizeBy: none
		sourceColumn: FWPeriodLabel

		annotation SummarizationSetBy = Automatic

	column FWStartOfYear
		dataType: string
		lineageTag: c787b945-a01a-436b-8900-4ff6e1007c9c
		summarizeBy: none
		sourceColumn: FWStartOfYear

		annotation SummarizationSetBy = Automatic

	column FWEndOfYear
		dataType: string
		lineageTag: 77652d45-3dc0-46fe-ba7e-ee4d7b858680
		summarizeBy: none
		sourceColumn: FWEndOfYear

		annotation SummarizationSetBy = Automatic

	column FWStartOfQuarter
		dataType: string
		lineageTag: b6e91150-12b6-4f5e-a175-296a490948ad
		summarizeBy: none
		sourceColumn: FWStartOfQuarter

		annotation SummarizationSetBy = Automatic

	column FWEndOfQuarter
		dataType: string
		lineageTag: 40649b63-e0b3-42d1-8584-c90eaaa5addc
		summarizeBy: none
		sourceColumn: FWEndOfQuarter

		annotation SummarizationSetBy = Automatic

	column FWStartOfMonth
		dataType: string
		lineageTag: 9bc6ea17-5ff1-4a9f-a31a-f54cc320efb9
		summarizeBy: none
		sourceColumn: FWStartOfMonth

		annotation SummarizationSetBy = Automatic

	column FWEndOfMonth
		dataType: string
		lineageTag: 4127e50e-ed1c-40d8-ae4e-40262d0949d7
		summarizeBy: none
		sourceColumn: FWEndOfMonth

		annotation SummarizationSetBy = Automatic

	column FWStartOfWeek
		dataType: string
		lineageTag: 776f4ba0-e8df-4e0f-bca4-0e7c5e5773fb
		summarizeBy: none
		sourceColumn: FWStartOfWeek

		annotation SummarizationSetBy = Automatic

	column FWEndOfWeek
		dataType: string
		lineageTag: ad8b936a-ec32-496c-b2da-4c7c65b2d100
		summarizeBy: none
		sourceColumn: FWEndOfWeek

		annotation SummarizationSetBy = Automatic

	column WeekDayNumber
		dataType: string
		lineageTag: 46351265-9921-46cf-9e42-fed580979e4a
		summarizeBy: none
		sourceColumn: WeekDayNumber

		annotation SummarizationSetBy = Automatic

	column WeekDayNameShort
		dataType: string
		lineageTag: d7df4581-63ed-4701-aa51-3ad8edf203de
		summarizeBy: none
		sourceColumn: WeekDayNameShort

		annotation SummarizationSetBy = Automatic

	column FWDayOfYearNumber
		dataType: string
		lineageTag: 8d80e45d-8673-4e7a-91d3-f4a3100c428d
		summarizeBy: none
		sourceColumn: FWDayOfYearNumber

		annotation SummarizationSetBy = Automatic

	column FWDayOfQuarterNumber
		dataType: string
		lineageTag: 24147730-9f14-46a5-b465-8469f7a7fb2e
		summarizeBy: none
		sourceColumn: FWDayOfQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWDayOfMonthNumber
		dataType: string
		lineageTag: cdab56e2-fe84-405f-8d25-092727d5a1bc
		summarizeBy: none
		sourceColumn: FWDayOfMonthNumber

		annotation SummarizationSetBy = Automatic

	column IsWorkingDay
		dataType: string
		lineageTag: 9d66e7e6-56b9-41ac-8d5f-3b91377c92ff
		summarizeBy: none
		sourceColumn: IsWorkingDay

		annotation SummarizationSetBy = Automatic

	column DayType
		dataType: string
		lineageTag: 2d3fe48b-867d-4a07-a41a-8acec8805485
		summarizeBy: none
		sourceColumn: DayType

		annotation SummarizationSetBy = Automatic

	column FWWeekInQuarterNumber
		dataType: string
		lineageTag: 3908fd85-14e6-4182-be7c-3c81257f30fb
		summarizeBy: none
		sourceColumn: FWWeekInQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWYearMonthLabel
		dataType: string
		lineageTag: 6e61ab58-29f4-4d26-957d-64cc7bac56dd
		summarizeBy: none
		sourceColumn: FWYearMonthLabel

		annotation SummarizationSetBy = Automatic

	column FWYearQuarterLabel
		dataType: string
		lineageTag: 33732bc2-f6d2-4966-97c1-58a25e870f52
		summarizeBy: none
		sourceColumn: FWYearQuarterLabel

		annotation SummarizationSetBy = Automatic

	partition Dates = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "dates" ),
				    ChangedType = Table.TransformColumnTypes (
				        Source,
				        {
				            { "Date", type date },
				            { "DateKey", Int64.Type },
				            { "Year", Int64.Type },
				            { "IsYearStart", Int64.Type },
				            { "IsYearEnd", Int64.Type },
				            { "Quarter", Int64.Type },
				            { "QuarterStartDate", type date },
				            { "QuarterEndDate", type date },
				            { "IsQuarterStart", Int64.Type },
				            { "IsQuarterEnd", Int64.Type },
				            { "QuarterYear", type text },
				            { "Month", Int64.Type },
				            { "MonthName", type text },
				            { "MonthShort", type text },
				            { "MonthStartDate", type date },
				            { "MonthEndDate", type date },
				            { "MonthYear", type date },
				            { "MonthYearNumber", Int64.Type },
				            { "CalendarMonthIndex", Int64.Type },
				            { "CalendarQuarterIndex", Int64.Type },
				            { "IsMonthStart", Int64.Type },
				            { "IsMonthEnd", Int64.Type },
				            { "WeekOfMonth", Int64.Type },
				            { "Day", Int64.Type },
				            { "DayName", type text },
				            { "DayShort", type text },
				            { "DayOfYear", Int64.Type },
				            { "DayOfWeek", Int64.Type },
				            { "IsWeekend", Int64.Type },
				            { "IsBusinessDay", Int64.Type },
				            { "NextBusinessDay", type date },
				            { "PreviousBusinessDay", type date },
				            { "IsToday", Int64.Type },
				            { "IsCurrentYear", Int64.Type },
				            { "IsCurrentMonth", Int64.Type },
				            { "IsCurrentQuarter", Int64.Type },
				            { "CurrentDayOffset", Int64.Type }
				        }
				    )
				in
				    ChangedType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

