table Dates
	lineageTag: 1e93e289-4d40-485f-9fbc-7760c3c5e1fd
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 3fd4def5-f7ac-43bb-b84a-3bab249d71e1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 39c1bef1-cb8a-4c3f-8251-70835117b54d
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 996eb0fd-712d-4c55-b1e1-c3fb6938ba86
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column IsYearStart
		dataType: int64
		formatString: 0
		lineageTag: 0fa01c5a-256d-4a9b-8846-df82a8e04316
		summarizeBy: sum
		sourceColumn: IsYearStart

		annotation SummarizationSetBy = Automatic

	column IsYearEnd
		dataType: int64
		formatString: 0
		lineageTag: e01fa196-d101-42f9-8ed9-a96013bf317d
		summarizeBy: sum
		sourceColumn: IsYearEnd

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 45ccab9c-ce97-43bf-8e64-e11a01b2663d
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c461ebcb-c06a-4fef-916a-e5bcb1fb8584
		summarizeBy: none
		sourceColumn: QuarterStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QuarterEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: dc499a69-273c-4b3b-a9b8-b0ba8bb8a289
		summarizeBy: none
		sourceColumn: QuarterEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsQuarterStart
		dataType: int64
		formatString: 0
		lineageTag: ccb9f3a0-81eb-4680-8416-4336a5807833
		summarizeBy: sum
		sourceColumn: IsQuarterStart

		annotation SummarizationSetBy = Automatic

	column IsQuarterEnd
		dataType: int64
		formatString: 0
		lineageTag: e42a4d4e-1e5a-46b3-98c2-594bc49b72f2
		summarizeBy: sum
		sourceColumn: IsQuarterEnd

		annotation SummarizationSetBy = Automatic

	column QuarterYear
		dataType: string
		lineageTag: 99dacc30-46c9-41cd-b8bc-02a7917d57b0
		summarizeBy: none
		sourceColumn: QuarterYear

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 5de2751c-c920-47e7-ad61-50362f65a8dd
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1c1b18b8-f048-48be-8ea1-4b1b458d11b5
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: 629c62a1-d4cf-47d5-ba88-01888209e775
		summarizeBy: none
		sourceColumn: MonthShort

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e1d2c99f-5076-4a6a-b114-ea862dbd50c8
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2453504c-d732-4600-a8e4-0519ce4281a9
		summarizeBy: none
		sourceColumn: MonthEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: dec1a8fb-1746-4776-8c7c-5e32a44bd907
		summarizeBy: none
		sourceColumn: MonthYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthYearNumber
		dataType: int64
		formatString: 0
		lineageTag: c2d4c82e-8707-4d57-8ddb-8f87e1074676
		summarizeBy: sum
		sourceColumn: MonthYearNumber

		annotation SummarizationSetBy = Automatic

	column CalendarMonthIndex
		dataType: int64
		formatString: 0
		lineageTag: 3a2407da-1f0a-490a-b6ec-cfa0af5c409d
		summarizeBy: sum
		sourceColumn: CalendarMonthIndex

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterIndex
		dataType: int64
		formatString: 0
		lineageTag: 569a30fa-6067-48fd-954c-2c2aa675e9e2
		summarizeBy: sum
		sourceColumn: CalendarQuarterIndex

		annotation SummarizationSetBy = Automatic

	column IsMonthStart
		dataType: int64
		formatString: 0
		lineageTag: 7ba9a583-cc65-49c4-bfae-4ef5cabe119d
		summarizeBy: sum
		sourceColumn: IsMonthStart

		annotation SummarizationSetBy = Automatic

	column IsMonthEnd
		dataType: int64
		formatString: 0
		lineageTag: c296b142-d065-41b6-be89-9b0ab2f75b51
		summarizeBy: sum
		sourceColumn: IsMonthEnd

		annotation SummarizationSetBy = Automatic

	column WeekOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 5427df1a-095d-45a6-b3a1-96273463af73
		summarizeBy: sum
		sourceColumn: WeekOfMonth

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 1a997df4-2abb-4de1-8d9d-8305dbd43ed1
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 79ec9d90-0bf8-455b-b330-6d5ef21a0ed3
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: efe73c27-c199-4ae3-b85c-e610acda1698
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column DayOfYear
		dataType: int64
		formatString: 0
		lineageTag: 1a8fe719-2776-4cef-8344-f4251db4e5fa
		summarizeBy: sum
		sourceColumn: DayOfYear

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 7d6e8180-ddfd-4ad8-bdb6-1f43015c81b3
		summarizeBy: sum
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: int64
		formatString: 0
		lineageTag: 4d167d05-7c47-44dd-bf28-0da4c96613b6
		summarizeBy: sum
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsBusinessDay
		dataType: int64
		formatString: 0
		lineageTag: 1f5ca372-3aa6-4b9a-b2a9-fb547bd03381
		summarizeBy: sum
		sourceColumn: IsBusinessDay

		annotation SummarizationSetBy = Automatic

	column NextBusinessDay
		dataType: dateTime
		formatString: Long Date
		lineageTag: 05d82fbc-a2c9-49a1-ac20-9079af2e0bc7
		summarizeBy: none
		sourceColumn: NextBusinessDay

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PreviousBusinessDay
		dataType: dateTime
		formatString: Long Date
		lineageTag: e3c83809-8168-44ff-8169-b9c8dd4e84f9
		summarizeBy: none
		sourceColumn: PreviousBusinessDay

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsToday
		dataType: int64
		formatString: 0
		lineageTag: 98462bd4-960c-46d6-8406-bf743cef09f9
		summarizeBy: sum
		sourceColumn: IsToday

		annotation SummarizationSetBy = Automatic

	column IsCurrentYear
		dataType: int64
		formatString: 0
		lineageTag: c2cba7b4-0a8f-47e5-a4dd-4c8e3c651b4b
		summarizeBy: sum
		sourceColumn: IsCurrentYear

		annotation SummarizationSetBy = Automatic

	column IsCurrentMonth
		dataType: int64
		formatString: 0
		lineageTag: 84c60459-6920-4c6a-aa08-c727841407ba
		summarizeBy: sum
		sourceColumn: IsCurrentMonth

		annotation SummarizationSetBy = Automatic

	column IsCurrentQuarter
		dataType: int64
		formatString: 0
		lineageTag: 4323b79a-710a-437c-a338-72047e9d261a
		summarizeBy: sum
		sourceColumn: IsCurrentQuarter

		annotation SummarizationSetBy = Automatic

	column CurrentDayOffset
		dataType: int64
		formatString: 0
		lineageTag: 59701842-1673-4a62-9f00-2dc46610c9d6
		summarizeBy: sum
		sourceColumn: CurrentDayOffset

		annotation SummarizationSetBy = Automatic

	column SequentialDayIndex
		dataType: int64
		formatString: 0
		lineageTag: 0bf07774-6920-4918-9934-834a9f937813
		summarizeBy: sum
		sourceColumn: SequentialDayIndex

		annotation SummarizationSetBy = Automatic

	column YearQuarterKey
		dataType: int64
		formatString: 0
		lineageTag: 771e290e-5d47-4f0c-b2bc-4e393e50ae6f
		summarizeBy: count
		sourceColumn: YearQuarterKey

		annotation SummarizationSetBy = Automatic

	column YearOffset
		dataType: int64
		formatString: 0
		lineageTag: 242c8837-97e8-4434-a2cb-33d9a80f4bf5
		summarizeBy: sum
		sourceColumn: YearOffset

		annotation SummarizationSetBy = Automatic

	column CalendarMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: 72d08d39-73b5-4677-9bc3-d27be5f89b41
		summarizeBy: sum
		sourceColumn: CalendarMonthOffset

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 06f4c3ec-25bb-4a6a-ad59-e678783f20d0
		summarizeBy: sum
		sourceColumn: CalendarQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FiscalYearStartYear
		dataType: int64
		formatString: 0
		lineageTag: bbc687a1-6d13-41cf-9472-b27524578a1e
		summarizeBy: sum
		sourceColumn: FiscalYearStartYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 73322518-5440-4a33-aee0-3d9c2c66d994
		summarizeBy: sum
		sourceColumn: FiscalMonthNumber

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 5e916cae-c023-4013-9e9d-8c8f561a0b44
		summarizeBy: sum
		sourceColumn: FiscalQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FiscalMonthIndex
		dataType: int64
		formatString: 0
		lineageTag: 58fde4a9-4fe9-43d7-8aa1-485ad1c784e1
		summarizeBy: sum
		sourceColumn: FiscalMonthIndex

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterIndex
		dataType: int64
		formatString: 0
		lineageTag: fe97a832-06e0-45a6-a701-dfdcea0adc28
		summarizeBy: sum
		sourceColumn: FiscalQuarterIndex

		annotation SummarizationSetBy = Automatic

	column FiscalMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: b6b720b0-9c62-43a3-bb10-f5cd96ee0073
		summarizeBy: sum
		sourceColumn: FiscalMonthOffset

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 7ffa2d3e-c928-4b87-9756-c193aa4f6c7a
		summarizeBy: sum
		sourceColumn: FiscalQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterName
		dataType: string
		lineageTag: 58360950-77f4-4c4b-a8f1-02a0260bae83
		summarizeBy: none
		sourceColumn: FiscalQuarterName

		annotation SummarizationSetBy = Automatic

	column FiscalYearBin
		dataType: string
		lineageTag: 188252a4-19a2-482e-bd01-586e9f03d8d8
		summarizeBy: none
		sourceColumn: FiscalYearBin

		annotation SummarizationSetBy = Automatic

	column FiscalYearStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b9bec629-8ad3-462b-ac4b-6c9ae29ec02b
		summarizeBy: none
		sourceColumn: FiscalYearStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalYearEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a1756cb5-b5ba-4adc-a118-94a392251d59
		summarizeBy: none
		sourceColumn: FiscalYearEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalQuarterStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: f006a353-6c14-4ff0-9de9-2a9f8399779e
		summarizeBy: none
		sourceColumn: FiscalQuarterStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalQuarterEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b6b405bd-8725-4de0-b722-bc9c30bc80a9
		summarizeBy: none
		sourceColumn: FiscalQuarterEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsFiscalYearStart
		dataType: int64
		formatString: 0
		lineageTag: da35991b-d03e-4873-8d32-048b3da4173c
		summarizeBy: sum
		sourceColumn: IsFiscalYearStart

		annotation SummarizationSetBy = Automatic

	column IsFiscalYearEnd
		dataType: int64
		formatString: 0
		lineageTag: f9897daf-3491-4d76-ad63-b9159097a71e
		summarizeBy: sum
		sourceColumn: IsFiscalYearEnd

		annotation SummarizationSetBy = Automatic

	column IsFiscalQuarterStart
		dataType: int64
		formatString: 0
		lineageTag: fa4491ad-1f92-4534-9f79-63c3a6d097e1
		summarizeBy: sum
		sourceColumn: IsFiscalQuarterStart

		annotation SummarizationSetBy = Automatic

	column IsFiscalQuarterEnd
		dataType: int64
		formatString: 0
		lineageTag: 7aaebb5f-46ce-4291-9e3c-25df139391ee
		summarizeBy: sum
		sourceColumn: IsFiscalQuarterEnd

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: 9303d5d5-0ff8-4504-9267-c40b09ee8837
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalYearLabel
		dataType: string
		lineageTag: 35d5d71c-a9d6-4b65-87a1-6a09e70b1406
		summarizeBy: none
		sourceColumn: FiscalYearLabel

		annotation SummarizationSetBy = Automatic

	column FiscalSystem
		dataType: string
		lineageTag: 6332f39c-04d0-46b3-b876-84f03ec45bdd
		summarizeBy: none
		sourceColumn: FiscalSystem

		annotation SummarizationSetBy = Automatic

	column WeeklyFiscalSystem
		dataType: string
		lineageTag: 61709f01-fb55-49ab-95e2-ade6214f3a74
		summarizeBy: none
		sourceColumn: WeeklyFiscalSystem

		annotation SummarizationSetBy = Automatic

	column FWYearNumber
		dataType: int64
		formatString: 0
		lineageTag: ec52d54b-8b28-4d1a-8200-a4c9a15966ef
		summarizeBy: sum
		sourceColumn: FWYearNumber

		annotation SummarizationSetBy = Automatic

	column FWYearLabel
		dataType: string
		lineageTag: b45fc5bc-567c-4d16-a449-d57dd3f5b710
		summarizeBy: none
		sourceColumn: FWYearLabel

		annotation SummarizationSetBy = Automatic

	column FWQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 8fb7a845-2ce0-4581-8fcd-286965bb088f
		summarizeBy: sum
		sourceColumn: FWQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWQuarterLabel
		dataType: string
		lineageTag: 64def9a9-8728-4348-a370-18d5774530ba
		summarizeBy: none
		sourceColumn: FWQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FWYearQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 9fec3a7b-dd97-4af6-b41e-e6d891934790
		summarizeBy: sum
		sourceColumn: FWYearQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWYearQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: dcc00a61-afe4-49b1-8cf3-6fd65253670c
		summarizeBy: sum
		sourceColumn: FWYearQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FWMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: fad42e30-51ca-442a-9c38-1d629fc3a57c
		summarizeBy: sum
		sourceColumn: FWMonthNumber

		annotation SummarizationSetBy = Automatic

	column FWMonthLabel
		dataType: string
		lineageTag: eac70870-5d9e-4114-9738-5fea08e3d219
		summarizeBy: none
		sourceColumn: FWMonthLabel

		annotation SummarizationSetBy = Automatic

	column FWYearMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: b11dd302-33a7-4375-9625-f29489831e5e
		summarizeBy: sum
		sourceColumn: FWYearMonthNumber

		annotation SummarizationSetBy = Automatic

	column FWYearMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: f8003426-2384-4965-a7d7-6723e13ec94e
		summarizeBy: sum
		sourceColumn: FWYearMonthOffset

		annotation SummarizationSetBy = Automatic

	column FWWeekNumber
		dataType: int64
		formatString: 0
		lineageTag: 88efcd1a-4e9f-4135-902f-d3037dfc9a79
		summarizeBy: sum
		sourceColumn: FWWeekNumber

		annotation SummarizationSetBy = Automatic

	column FWWeekLabel
		dataType: string
		lineageTag: ef2386ed-e097-4959-9dec-154652c63965
		summarizeBy: none
		sourceColumn: FWWeekLabel

		annotation SummarizationSetBy = Automatic

	column FWYearWeekNumber
		dataType: int64
		formatString: 0
		lineageTag: 98a8df25-33de-4202-b1de-a026188b8599
		summarizeBy: sum
		sourceColumn: FWYearWeekNumber

		annotation SummarizationSetBy = Automatic

	column FWYearWeekOffset
		dataType: int64
		formatString: 0
		lineageTag: 9745c475-cd53-44d8-8630-f7a17bfd404c
		summarizeBy: sum
		sourceColumn: FWYearWeekOffset

		annotation SummarizationSetBy = Automatic

	column FWPeriodNumber
		dataType: int64
		formatString: 0
		lineageTag: 2d1b83f2-b930-4093-9edd-cb26c2534c39
		summarizeBy: sum
		sourceColumn: FWPeriodNumber

		annotation SummarizationSetBy = Automatic

	column FWPeriodLabel
		dataType: string
		lineageTag: 1a536e94-6622-4824-86ea-6d616729dc34
		summarizeBy: none
		sourceColumn: FWPeriodLabel

		annotation SummarizationSetBy = Automatic

	column FWStartOfYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: d676819e-c272-435d-9f3a-94018482cc33
		summarizeBy: none
		sourceColumn: FWStartOfYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: 09a3f4f7-433e-48cb-84de-c9bb09a10cb4
		summarizeBy: none
		sourceColumn: FWEndOfYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWStartOfQuarter
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7acd7774-8e19-4bb7-ac5c-b63e0a0f2e4d
		summarizeBy: none
		sourceColumn: FWStartOfQuarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfQuarter
		dataType: dateTime
		formatString: Long Date
		lineageTag: aa7f1be8-c3e3-4390-8a98-c79c5a43f1cc
		summarizeBy: none
		sourceColumn: FWEndOfQuarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWStartOfMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: 55fde2b8-17ea-4ef3-9384-66bdbdb3fddc
		summarizeBy: none
		sourceColumn: FWStartOfMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: ab1fd209-8bcd-4b35-96fd-da084b947e40
		summarizeBy: none
		sourceColumn: FWEndOfMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWStartOfWeek
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4ac3dc48-62ad-4a81-bca6-4ee656cdab57
		summarizeBy: none
		sourceColumn: FWStartOfWeek

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfWeek
		dataType: dateTime
		formatString: Long Date
		lineageTag: e07b240c-d4fe-40bd-85d5-d76aa79ecddd
		summarizeBy: none
		sourceColumn: FWEndOfWeek

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekDayNumber
		dataType: int64
		formatString: 0
		lineageTag: 7956acbd-be72-47b1-b9cb-719f037709f5
		summarizeBy: sum
		sourceColumn: WeekDayNumber

		annotation SummarizationSetBy = Automatic

	column WeekDayNameShort
		dataType: string
		lineageTag: 39275abd-b3a7-4f7a-aa2d-663e372f5e7e
		summarizeBy: none
		sourceColumn: WeekDayNameShort

		annotation SummarizationSetBy = Automatic

	column FWDayOfYearNumber
		dataType: int64
		formatString: 0
		lineageTag: db5b2a47-c8a5-41ce-b7f0-56165458e204
		summarizeBy: sum
		sourceColumn: FWDayOfYearNumber

		annotation SummarizationSetBy = Automatic

	column FWDayOfQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: bcaae6c3-ed25-44c1-9737-7edba966d666
		summarizeBy: sum
		sourceColumn: FWDayOfQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWDayOfMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 168fecae-efa2-40b0-925b-cf8034a28d2b
		summarizeBy: sum
		sourceColumn: FWDayOfMonthNumber

		annotation SummarizationSetBy = Automatic

	column IsWorkingDay
		dataType: int64
		formatString: 0
		lineageTag: 6242470c-061f-4122-816b-980f2a133735
		summarizeBy: sum
		sourceColumn: IsWorkingDay

		annotation SummarizationSetBy = Automatic

	column DayType
		dataType: string
		lineageTag: c8ed1c50-e19d-41fe-9547-8140fc66eb95
		summarizeBy: none
		sourceColumn: DayType

		annotation SummarizationSetBy = Automatic

	column FWWeekInQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: e99aa69b-263f-4d9c-8ab2-b5229d242915
		summarizeBy: sum
		sourceColumn: FWWeekInQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWYearMonthLabel
		dataType: string
		lineageTag: ad23945a-6553-492d-9fd6-c87f86b98ed8
		summarizeBy: none
		sourceColumn: FWYearMonthLabel

		annotation SummarizationSetBy = Automatic

	partition Dates = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "dates" ),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type date}, {"DateKey", Int64.Type}, {"SequentialDayIndex", Int64.Type}, {"Year", Int64.Type}, {"Quarter", Int64.Type}, {"QuarterStartDate", type date}, {"QuarterEndDate", type date}, {"QuarterYear", type text}, {"Month", Int64.Type}, {"MonthName", type text}, {"MonthShort", type text}, {"MonthStartDate", type date}, {"MonthEndDate", type date}, {"MonthYear", type date}, {"MonthYearNumber", Int64.Type}, {"YearQuarterKey", Int64.Type}, {"CalendarMonthIndex", Int64.Type}, {"CalendarQuarterIndex", Int64.Type}, {"WeekOfMonth", Int64.Type}, {"Day", Int64.Type}, {"DayName", type text}, {"DayShort", type text}, {"DayOfYear", Int64.Type}, {"DayOfWeek", Int64.Type}, {"IsWeekend", Int64.Type}, {"IsBusinessDay", Int64.Type}, {"NextBusinessDay", type date}, {"PreviousBusinessDay", type date}, {"IsYearStart", Int64.Type}, {"IsYearEnd", Int64.Type}, {"IsQuarterStart", Int64.Type}, {"IsQuarterEnd", Int64.Type}, {"IsMonthStart", Int64.Type}, {"IsMonthEnd", Int64.Type}, {"IsToday", Int64.Type}, {"IsCurrentYear", Int64.Type}, {"IsCurrentMonth", Int64.Type}, {"IsCurrentQuarter", Int64.Type}, {"CurrentDayOffset", Int64.Type}, {"YearOffset", Int64.Type}, {"CalendarMonthOffset", Int64.Type}, {"CalendarQuarterOffset", Int64.Type}, {"FiscalYearStartYear", Int64.Type}, {"FiscalMonthNumber", Int64.Type}, {"FiscalQuarterNumber", Int64.Type}, {"FiscalMonthIndex", Int64.Type}, {"FiscalQuarterIndex", Int64.Type}, {"FiscalMonthOffset", Int64.Type}, {"FiscalQuarterOffset", Int64.Type}, {"FiscalQuarterName", type text}, {"FiscalYearBin", type text}, {"FiscalYearStartDate", type date}, {"FiscalYearEndDate", type date}, {"FiscalQuarterStartDate", type date}, {"FiscalQuarterEndDate", type date}, {"IsFiscalYearStart", Int64.Type}, {"IsFiscalYearEnd", Int64.Type}, {"IsFiscalQuarterStart", Int64.Type}, {"IsFiscalQuarterEnd", Int64.Type}, {"FiscalYear", Int64.Type}, {"FiscalYearLabel", type text}, {"FiscalSystem", type text}, {"WeeklyFiscalSystem", type text}, {"FWYearNumber", Int64.Type}, {"FWYearLabel", type text}, {"FWQuarterNumber", Int64.Type}, {"FWQuarterLabel", type text}, {"FWYearQuarterNumber", Int64.Type}, {"FWYearQuarterOffset", Int64.Type}, {"FWMonthNumber", Int64.Type}, {"FWMonthLabel", type text}, {"FWYearMonthNumber", Int64.Type}, {"FWYearMonthOffset", Int64.Type}, {"FWWeekNumber", Int64.Type}, {"FWWeekLabel", type text}, {"FWYearWeekNumber", Int64.Type}, {"FWYearWeekOffset", Int64.Type}, {"FWPeriodNumber", Int64.Type}, {"FWPeriodLabel", type text}, {"FWStartOfYear", type date}, {"FWEndOfYear", type date}, {"FWStartOfQuarter", type date}, {"FWEndOfQuarter", type date}, {"FWStartOfMonth", type date}, {"FWEndOfMonth", type date}, {"FWStartOfWeek", type date}, {"FWEndOfWeek", type date}, {"WeekDayNumber", Int64.Type}, {"WeekDayNameShort", type text}, {"FWDayOfYearNumber", Int64.Type}, {"FWDayOfQuarterNumber", Int64.Type}, {"FWDayOfMonthNumber", Int64.Type}, {"IsWorkingDay", Int64.Type}, {"DayType", type text}, {"FWWeekInQuarterNumber", Int64.Type}, {"FWYearMonthLabel", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

