table Geography
	lineageTag: e1efdba3-1f8e-4419-a2cc-15ee8ccae934

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: b6c43b13-0208-43d9-849c-703285b7fe7d
		summarizeBy: count
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: dc69bb8a-690d-4e9a-b19c-5af57549fc39
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 894c16d4-2c79-4475-9d53-01cd2e5c9da4
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 4bc0780d-695c-4c3a-ab2a-e1e4a5b6310a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: string
		lineageTag: f536c8db-4899-43c1-84c7-992733e0937d
		summarizeBy: none
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

	column ISOCode
		dataType: string
		lineageTag: e7b6a0d1-bb61-4d2f-bded-0e6ff917c496
		summarizeBy: none
		sourceColumn: ISOCode

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 7017c8f4-f92f-4b04-98e3-571aa3da5421
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 8d22528c-f931-4a6e-bb86-cc6c56e1222d
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Timezone
		dataType: string
		lineageTag: eefc99f9-68eb-4ccc-9641-655d1a41543d
		summarizeBy: none
		sourceColumn: Timezone

		annotation SummarizationSetBy = Automatic

	column Population
		dataType: int64
		formatString: 0
		lineageTag: 827c7138-a2fb-4c51-8ee2-6bbf2e70763d
		summarizeBy: sum
		sourceColumn: Population

		annotation SummarizationSetBy = Automatic

	partition Geography = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "geography" ),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"GeographyKey", Int64.Type}, {"City", type text}, {"State", type text}, {"Country", type text}, {"Continent", type text}, {"ISOCode", type text}, {"Latitude", type number}, {"Longitude", type number}, {"Timezone", type text}, {"Population", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

