table MeasureTable
	lineageTag: a79715bc-3f48-4e38-a742-77f338a1070a

	measure '# Customers' =
			
			DISTINCTCOUNT ( Sales[CustomerKey] )
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 174e935b-1f31-468a-b9a3-8e4c43aa2487

	measure 'Avg Delivery Lag' = ```
			
			AVERAGEX(
			    Sales,
			    DATEDIFF(Sales[OrderDate], Sales[DeliveryDate], DAY)
			)
			
			```
		displayFolder: 01 - Base Measures
		lineageTag: 0f58abd1-1a98-4bda-bdfe-aa63c2fddeee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cost Amount' = ```
			
			SUMX ( 
			    Sales, 
			    Sales[Quantity] * Sales[UnitCost]
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 316bc9a9-7992-4938-830c-767ce80a76be

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Due vs Delivery' = ```
			
			SUMX ( 
			    Sales,
			    DATEDIFF ( Sales[DueDate], Sales[DeliveryDate],  DAY )
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 1e7b72ab-ed2c-4cf0-9ef5-7cb7b4c05124

	measure 'Employee Sales by Store Assgn.' = ```
			
			CALCULATE ( 
			    [Sales Amount],
			    TREATAS ( 
			        GENERATE ( 
			            SUMMARIZE ( 
			                EmployeeStoreAssignment, 
			                EmployeeStoreAssignment[StoreKey],
			                Employee[EmployeeKey]
			            ),
			            DATESBETWEEN ( 
			                Dates[Date],
			                CALCULATE ( MIN ( EmployeeStoreAssignment[StartDate] ) ),
			                CALCULATE ( MAX ( EmployeeStoreAssignment[EndDate] ) )
			            )
			        ),
			        Sales[StoreKey],
			        Sales[EmployeeKey],
			        Dates[Date]
			    )
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 9ea4b942-f332-4920-b527-413f495e5a02

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Max List Price' = MAX ( Products[ListPrice] )
		displayFolder: 01 - Base Measures
		lineageTag: 2219c523-d345-4f7f-a9f7-d553ed7449c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min List Price' = MIN ( Products[ListPrice] )
		displayFolder: 01 - Base Measures
		lineageTag: 81811407-e72b-4e9b-8c3e-c35c2065f19c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Order vs Delivery' = ```
			
			SUMX ( 
			    Sales,
			    DATEDIFF ( Sales[OrderDate], Sales[DeliveryDate],  DAY )
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 11d337b2-9fac-4fee-b262-810c534d7661

	measure 'Profit Amount' =
			
			[Sales Amount] - [Cost Amount]
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: a95a2156-9a97-45f8-b9a9-08a4ef5a8d06

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Sales Amount' = ```
			
			SUMX ( 
			    Sales,
			    Sales[Quantity] * Sales[NetPrice]
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 0d511203-d4fa-4fbf-bed4-84ce7a184526

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Transactions =
			
			COUNTROWS ( Sales )
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: f941d2a9-2c52-4441-ba75-afa6c2f91413

	column Column1
		dataType: string
		isHidden
		lineageTag: 2c629aff-ace3-49e6-9e5a-e9c089996261
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition MeasureTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

