table Returns
	lineageTag: e5942e12-813c-4803-97fb-879b388a5987

	column OrderNumber
		dataType: int64
		formatString: 0
		lineageTag: 6f44264e-b30f-45fd-bc01-cb9ec8c8f392
		summarizeBy: sum
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column OrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 00d34491-6def-4c63-8e04-3d7a1e728452
		summarizeBy: sum
		sourceColumn: OrderLineNumber

		annotation SummarizationSetBy = Automatic

	column ReturnDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9451fe9a-f083-4190-8d6c-958bc37bcc4f
		summarizeBy: none
		sourceColumn: ReturnDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ReturnReasonKey
		dataType: int64
		formatString: 0
		lineageTag: 319bbbca-fc01-4988-aaf9-cb327adf50c7
		summarizeBy: count
		sourceColumn: ReturnReasonKey

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: d0a276e4-0664-4bf4-90f8-18f4b84bbb33
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	column ReturnNetPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 960bbb07-8532-45cc-a0be-e6c2de7189c0
		summarizeBy: sum
		sourceColumn: ReturnNetPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ReturnEventKey
		dataType: int64
		formatString: 0
		lineageTag: 8692fdd7-113c-4d32-8ac6-601e19260d9a
		summarizeBy: count
		sourceColumn: ReturnEventKey

		annotation SummarizationSetBy = Automatic

	column ReturnSequence
		dataType: int64
		formatString: 0
		lineageTag: 3b3957a1-a1f6-4653-91f7-aed712be0499
		summarizeBy: sum
		sourceColumn: ReturnSequence

		annotation SummarizationSetBy = Automatic

	partition Returns = m
		mode: import
		queryGroup: Fact\SecondaryFacts
		source =
				let
				    Source = Folder.Files ( ContosoFolder & "\facts\returns" ),
				    RemoveCols = Table.SelectColumns ( Source, { "Content" } ),
				    RemoveHidden = Table.SelectRows ( RemoveCols, each [Attributes]?[Hidden]? <> true ),
				    InvokeCustom = Table.AddColumn (
				        RemoveHidden,
				        "Transform File",
				        each Transform_Returns_File ( [Content] )
				    ),
				    RemoveOtherCol = Table.SelectColumns ( InvokeCustom, { "Transform File" } ),
				    CombineTables = Table.ExpandTableColumn (
				        RemoveOtherCol,
				        "Transform File",
				        Table.ColumnNames ( Transform_Returns_File ( Sample_File_Returns ) )
				    ),
				    ChangeType = Table.TransformColumnTypes(CombineTables,{{"OrderNumber", Int64.Type}, {"OrderLineNumber", Int64.Type}, {"ReturnDate", type date}, {"ReturnReasonKey", Int64.Type}, {"ReturnQuantity", Int64.Type}, {"ReturnNetPrice", Currency.Type}, {"ReturnEventKey", Int64.Type}, {"ReturnSequence", Int64.Type}})
				in
				    ChangeType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

