name: Bug report
description: Report a problem.
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Describe the issue. Add logs if you have them.
      placeholder: "Example: Generator crashes when ..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (optional)
      render: text
      placeholder: "Paste traceback/output here..."
    validations:
      required: false
