name: Feature request
description: Propose a change or new capability.
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Minimal feature request. Keep it testable and backward-compatible.

  - type: textarea
    id: request
    attributes:
      label: What do you want and why?
      description: Problem + proposed solution (include expected behavior).
      placeholder: |
        Problem:
        - ...

        Proposal:
        - ...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria (optional)
      description: A short checklist of what “done” means.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes / compatibility impact (optional)
      description: Mention config keys, breaking changes, perf impact, etc.
      placeholder: |
        - New key(s): ...
        - Default behavior unchanged: yes/no
        - Risk: ...
    validations:
      required: false
