table Employee
	lineageTag: eb2c1c06-19de-4198-af4f-bc502969041c

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: b40f50e4-207c-43e2-a1f5-32e805e6164f
		summarizeBy: count
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = Automatic

	column ParentEmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 8f7ebef0-f141-4249-9993-d95c92c5ec42
		summarizeBy: count
		sourceColumn: ParentEmployeeKey

		annotation SummarizationSetBy = Automatic

	column EmployeeName
		dataType: string
		lineageTag: 3684f5c5-dcb1-4470-948f-287df0369c1b
		summarizeBy: none
		sourceColumn: EmployeeName

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 5767cc39-a895-46a8-81a2-760af4f2c1d5
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column OrgLevel
		dataType: int64
		formatString: 0
		lineageTag: 22436d44-af09-4faa-91d8-9d5494d967c8
		summarizeBy: sum
		sourceColumn: OrgLevel

		annotation SummarizationSetBy = Automatic

	column OrgUnitType
		dataType: string
		lineageTag: 671e0d9a-4cb8-469f-889d-924eeb2dc05b
		summarizeBy: none
		sourceColumn: OrgUnitType

		annotation SummarizationSetBy = Automatic

	column RegionId
		dataType: int64
		formatString: 0
		lineageTag: 2565810e-843d-42a2-8328-62127668ea15
		summarizeBy: count
		sourceColumn: RegionId

		annotation SummarizationSetBy = Automatic

	column DistrictId
		dataType: int64
		formatString: 0
		lineageTag: 0323bd8b-2078-468a-ac94-4fecad96c765
		summarizeBy: count
		sourceColumn: DistrictId

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 4fb15251-0764-4422-aa73-afb6b61ac2e2
		summarizeBy: count
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: 87e303df-dd16-49c8-8cd5-904e64e23103
		summarizeBy: count
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d325ddf3-5140-4e32-8973-5bb3208de944
		summarizeBy: none
		sourceColumn: HireDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column TerminationDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 1033a77e-9a74-4ffe-a763-b79e533d7071
		summarizeBy: none
		sourceColumn: TerminationDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column TerminationReason
		dataType: string
		lineageTag: fa0ffd6f-e9f8-4dc3-93ef-a98c9ccdcbcc
		summarizeBy: none
		sourceColumn: TerminationReason

		annotation SummarizationSetBy = Automatic

	column IsActive
		dataType: int64
		formatString: 0
		lineageTag: 92ddbede-c993-4b4d-a33f-e6b38924a848
		summarizeBy: sum
		sourceColumn: IsActive

		annotation SummarizationSetBy = Automatic

	column EmploymentType
		dataType: string
		lineageTag: 4ea9be41-6370-4edf-8ebb-574030f69865
		summarizeBy: none
		sourceColumn: EmploymentType

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: bd0a9efe-0378-4533-83b8-804fc9b69b00
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gender
		dataType: string
		lineageTag: a6624b3a-622a-4d2f-90c9-23061f226921
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 4a8e05b0-4906-4b4f-9b9a-fd15ffc35ee0
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: a1caee98-5956-4b28-8522-8201e6fc0c33
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column MiddleName
		dataType: string
		lineageTag: 759b9e1e-7952-4281-ab70-3b49d7529f48
		summarizeBy: none
		sourceColumn: MiddleName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: cfd162e7-7a95-4373-877b-7098392d9de1
		summarizeBy: none
		sourceColumn: BirthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column MaritalStatus
		dataType: string
		lineageTag: e8e9a7da-f634-4686-bca3-0c2318057bef
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 924a093c-a2b2-47e3-b1d0-910842b1e86b
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 9c0ba682-b483-4fc1-a508-39167e09d104
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column EmergencyContactName
		dataType: string
		lineageTag: 65f43cea-d4c5-43c7-a132-c5769b75e34b
		summarizeBy: none
		sourceColumn: EmergencyContactName

		annotation SummarizationSetBy = Automatic

	column EmergencyContactPhone
		dataType: string
		lineageTag: bc990207-6026-47de-ab4d-a97d0191becc
		summarizeBy: none
		sourceColumn: EmergencyContactPhone

		annotation SummarizationSetBy = Automatic

	column SalariedFlag
		dataType: int64
		formatString: 0
		lineageTag: b007c7b8-7b56-4262-bb3e-266f199c802e
		summarizeBy: sum
		sourceColumn: SalariedFlag

		annotation SummarizationSetBy = Automatic

	column PayFrequency
		dataType: int64
		formatString: 0
		lineageTag: 934daccf-b174-4a7c-bc20-f004b3b30cf4
		summarizeBy: sum
		sourceColumn: PayFrequency

		annotation SummarizationSetBy = Automatic

	column BaseRate
		dataType: double
		lineageTag: 58a6f258-42da-4aa2-8e3e-d5c3b2703a24
		summarizeBy: sum
		sourceColumn: BaseRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VacationHours
		dataType: int64
		formatString: 0
		lineageTag: 84e109eb-ecc6-44c0-8a5f-df242df31664
		summarizeBy: sum
		sourceColumn: VacationHours

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 83c16cd0-4d67-40bb-99d0-a587327a5725
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column SalesPersonFlag
		dataType: int64
		formatString: 0
		lineageTag: 0586e3c7-e1f3-48f1-b322-9c2ba4c4ad07
		summarizeBy: sum
		sourceColumn: SalesPersonFlag

		annotation SummarizationSetBy = Automatic

	column DepartmentName
		dataType: string
		lineageTag: e66d312a-6baf-44af-b848-19a551f1ec14
		summarizeBy: none
		sourceColumn: DepartmentName

		annotation SummarizationSetBy = Automatic

	partition Employee = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source      = FxReadParquetFile ( "dimensions\employees" ),
				    ChangedType = Table.TransformColumnTypes ( Source, { { "ParentEmployeeKey", Int64.Type } } )
				in
				    ChangedType

	annotation PBI_ResultType = Table

