table MeasureTable
	lineageTag: 0585b77d-b129-4c0e-9763-a29089eabcd3

	measure 'Cost Amount' = ```
			
			SUMX ( 
			    SalesOrderDetail, 
			    SalesOrderDetail[Quantity] * SalesOrderDetail[UnitCost]
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 161627e6-1af2-4474-94e3-8f71733d228e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Sales Amount' = ```
			
			SUMX ( 
			    SalesOrderDetail, 
			    SalesOrderDetail[Quantity] * SalesOrderDetail[NetPrice]
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 48d9e8b9-f997-475d-b363-973edb1d5bb3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Transactions =
			
			COUNTROWS ( SalesOrderDetail )
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: f941d2a9-2c52-4441-ba75-afa6c2f91413

	measure '# Customers' = ```
			
			CALCULATE ( 
			    DISTINCTCOUNT ( SalesOrderHeader[CustomerKey] ),
			    CROSSFILTER ( SalesOrderDetail[SalesOrderNumber], SalesOrderHeader[SalesOrderNumber], Both )
			)
			```
		formatString: 0
		displayFolder: 01 - Base Measures
		lineageTag: 6ec8f0ae-723d-46cd-b46d-b9c1cedc3068

	measure 'Profit Amount' =
			
			[Sales Amount] - [Cost Amount]
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 2a2235d4-e261-4801-84e5-a5284e715773

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Employee Sales by Store Assgn.' = ```
			
			CALCULATE ( 
			    [Sales Amount],
			    TREATAS ( 
			        GENERATE ( 
			            SUMMARIZE ( 
			                EmployeeStoreAssignment, 
			                EmployeeStoreAssignment[StoreKey],
			                Employee[EmployeeKey]
			            ),
			            DATESBETWEEN ( 
			                Dates[Date],
			                CALCULATE ( MIN ( EmployeeStoreAssignment[StartDate] ) ),
			                CALCULATE ( MAX ( EmployeeStoreAssignment[EndDate] ) )
			            )
			        ),
			        SalesOrderHeader[StoreKey],
			        SalesOrderHeader[SalesPersonEmployeeKey],
			        Dates[Date]
			    )
			)
			```
		formatString: #,0
		displayFolder: 01 - Base Measures
		lineageTag: 8d7be87d-7474-4424-9ae8-82393276bfb6

		annotation PBI_FormatHint = {"isDecimal":true}

	column Column1
		dataType: string
		isHidden
		lineageTag: edd2d66e-98a3-429e-8dc6-c41e7d5a3847
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition MeasureTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

