table SalesChannel
	lineageTag: 754b0e32-65c9-4018-a902-5287bfbbe2f4

	column SalesChannelKey
		dataType: int64
		formatString: 0
		lineageTag: 42a9a2e6-3717-4ed9-b312-93d1eb34fc6f
		summarizeBy: count
		sourceColumn: SalesChannelKey

		annotation SummarizationSetBy = Automatic

	column SalesChannel
		dataType: string
		lineageTag: b9d3527d-7f36-4167-b1e1-fdb8c8e9aff4
		summarizeBy: none
		sourceColumn: SalesChannel

		annotation SummarizationSetBy = Automatic

	column SalesChannelDescription
		dataType: string
		lineageTag: 5bedb25a-6ab6-4686-b8d8-bd6c4606a4b7
		summarizeBy: none
		sourceColumn: SalesChannelDescription

		annotation SummarizationSetBy = Automatic

	column ChannelGroup
		dataType: string
		lineageTag: 86067ba1-49f4-4c55-98df-301be60b1379
		summarizeBy: none
		sourceColumn: ChannelGroup

		annotation SummarizationSetBy = Automatic

	column ChannelGroupDescription
		dataType: string
		lineageTag: 2de32445-b849-4c0b-a5d2-05aee14bf90d
		summarizeBy: none
		sourceColumn: ChannelGroupDescription

		annotation SummarizationSetBy = Automatic

	column SalesChannelCode
		dataType: string
		lineageTag: 39b67101-3e67-4769-bc3b-dcaf26cb3050
		summarizeBy: none
		sourceColumn: SalesChannelCode

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: eb887182-d2de-46c0-a9da-835b8268720e
		summarizeBy: sum
		sourceColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	column IsDigital
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 19c9353c-8346-4a50-a7f1-52865a65677f
		summarizeBy: none
		sourceColumn: IsDigital

		annotation SummarizationSetBy = Automatic

	column IsPhysical
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d9c11d2a-a7a4-41ac-830e-ad4e36cf1023
		summarizeBy: none
		sourceColumn: IsPhysical

		annotation SummarizationSetBy = Automatic

	column IsThirdParty
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 445a33b3-6091-4bba-a1c3-0bc8ec58088b
		summarizeBy: none
		sourceColumn: IsThirdParty

		annotation SummarizationSetBy = Automatic

	column IsB2B
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 10a7e3a4-0c24-47f8-8e21-95919d5bb315
		summarizeBy: none
		sourceColumn: IsB2B

		annotation SummarizationSetBy = Automatic

	column IsAssisted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 275be710-51ac-4942-9172-bbefe17b668a
		summarizeBy: none
		sourceColumn: IsAssisted

		annotation SummarizationSetBy = Automatic

	column IsOwnedChannel
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b905b109-0c89-4934-a72f-123d5a026bc5
		summarizeBy: none
		sourceColumn: IsOwnedChannel

		annotation SummarizationSetBy = Automatic

	column Is24x7
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 574f7c84-0e6a-4ec9-b638-899f7d00eaf5
		summarizeBy: none
		sourceColumn: Is24x7

		annotation SummarizationSetBy = Automatic

	column OpenTime
		dataType: string
		lineageTag: 5cc8c465-31c8-4c9c-9432-069dd3e9a7cf
		summarizeBy: none
		sourceColumn: OpenTime

		annotation SummarizationSetBy = Automatic

	column CloseTime
		dataType: string
		lineageTag: 3e76bba1-9bb8-4de7-b915-38474858e30d
		summarizeBy: none
		sourceColumn: CloseTime

		annotation SummarizationSetBy = Automatic

	column CommissionRate
		dataType: double
		lineageTag: 0c570de0-0089-4296-b03c-2a75c1fad7d0
		summarizeBy: sum
		sourceColumn: CommissionRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TypicalFulfillmentDays
		dataType: int64
		formatString: 0
		lineageTag: fbc97fa2-98b5-4a0a-a3c0-32b4c15c1277
		summarizeBy: sum
		sourceColumn: TypicalFulfillmentDays

		annotation SummarizationSetBy = Automatic

	partition SalesChannel = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source     = FxReadParquetFile ( "dimensions\sales_channels" ),
				    ChangeType = Table.TransformColumnTypes ( Source, { { "SalesChannelKey", Int64.Type } } )
				in
				    ChangeType

	annotation PBI_ResultType = Table

