table SalesOrderHeader
	isHidden
	lineageTag: d0dfbf95-fd25-406d-8448-39d00c0572d6

	column SalesOrderNumber
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f17d5347-259c-4ea8-b3dc-4d2b48560f58
		summarizeBy: sum
		sourceColumn: SalesOrderNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: da63cb2e-08d8-4c46-a8a4-10e89d95b9f3
		summarizeBy: count
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 54f5f09c-2bf8-43cb-92cb-75c72ed4c6be
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsOrderDelayed
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a9c0c2c4-9ff2-4f61-aab2-911d995947be
		summarizeBy: sum
		sourceColumn: IsOrderDelayed

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 9730261e-fe29-4ccb-a30f-32af6e8fdd77
		summarizeBy: count
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column SalesPersonEmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: bfde07b1-d6c1-414b-9ca0-b64a76fa481d
		summarizeBy: count
		sourceColumn: SalesPersonEmployeeKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: c8e0b633-9a62-49ce-8a19-44d814140b64
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 22a60f23-3a66-4ca9-bbfb-1485115634d3
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column SalesChannelKey
		dataType: int64
		formatString: 0
		lineageTag: 24660e03-2991-42fc-b8b4-6d40a4e122c9
		summarizeBy: count
		sourceColumn: SalesChannelKey

		annotation SummarizationSetBy = Automatic

	column TimeKey
		dataType: int64
		formatString: 0
		lineageTag: 2b37b6db-21d3-47f2-93ab-cfa9c1f153a2
		summarizeBy: count
		sourceColumn: TimeKey

		annotation SummarizationSetBy = Automatic

	partition SalesOrderHeader = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = FxReadParquetFile ( "facts\sales_order_header" ),
				    ChangedType = Table.TransformColumnTypes (
				        Source,
				        { { "TimeKey", Int64.Type }, { "IsOrderDelayed", Int64.Type } }
				    )
				in
				    ChangedType

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

