createOrReplace

	ref table Sales

		measure '# Customers' =
				
				DISTINCTCOUNT ( Sales[CustomerKey] )
			formatString: 0
			displayFolder: 01 - Base Measures
			lineageTag: 6ec8f0ae-723d-46cd-b46d-b9c1cedc3068

		measure 'Cost Amount' = ```
				
				SUMX ( 
				    Sales, 
				    Sales[Quantity] * Sales[UnitCost]
				)
				```
			formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
			displayFolder: 01 - Base Measures
			lineageTag: 161627e6-1af2-4474-94e3-8f71733d228e

			annotation PBI_FormatHint = {"currencyCulture":"en-US"}

		measure 'Profit Amount' =
				
				[Sales Amount] - [Cost Amount]
			formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
			displayFolder: 01 - Base Measures
			lineageTag: a95a2156-9a97-45f8-b9a9-08a4ef5a8d06

			annotation PBI_FormatHint = {"currencyCulture":"en-US"}

		measure 'Sales Amount' = ```
				
				SUMX ( 
				    Sales, 
				    Sales[Quantity] * Sales[NetPrice]
				)
				```
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: 48d9e8b9-f997-475d-b363-973edb1d5bb3

			annotation PBI_FormatHint = {"isDecimal":true}

		measure Transactions =
				
				COUNTROWS ( Sales )
			formatString: 0
			displayFolder: 01 - Base Measures
			lineageTag: f941d2a9-2c52-4441-ba75-afa6c2f91413

