createOrReplace

	ref table MeasureTable

		measure '# Customers' = ```
				
				CALCULATE ( 
				    DISTINCTCOUNT ( SalesOrderHeader[CustomerKey] ),
				    CROSSFILTER ( SalesOrderDetail[SalesOrderNumber], SalesOrderHeader[SalesOrderNumber], Both )
				)
				```
			formatString: 0
			displayFolder: 01 - Base Measures
			lineageTag: 6ec8f0ae-723d-46cd-b46d-b9c1cedc3068

		measure 'Cost Amount' = ```
				
				SUMX ( 
				    SalesOrderDetail, 
				    SalesOrderDetail[Quantity] * SalesOrderDetail[UnitCost]
				)
				```
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: 161627e6-1af2-4474-94e3-8f71733d228e

			annotation PBI_FormatHint = {"isDecimal":true}

		measure 'Profit Amount' =
				
				[Sales Amount] - [Cost Amount]
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: 2a2235d4-e261-4801-84e5-a5284e715773

			annotation PBI_FormatHint = {"isDecimal":true}

		measure 'Sales Amount' = ```
				
				SUMX ( 
				    SalesOrderDetail, 
				    SalesOrderDetail[Quantity] * SalesOrderDetail[NetPrice]
				)
				```
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: 48d9e8b9-f997-475d-b363-973edb1d5bb3

			annotation PBI_FormatHint = {"isDecimal":true}

		measure Transactions =
				
				COUNTROWS ( SalesOrderDetail )
			formatString: #,0
			displayFolder: 01 - Base Measures
			lineageTag: f941d2a9-2c52-4441-ba75-afa6c2f91413

