table Dates
	lineageTag: 1e93e289-4d40-485f-9fbc-7760c3c5e1fd
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 3fd4def5-f7ac-43bb-b84a-3bab249d71e1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 39c1bef1-cb8a-4c3f-8251-70835117b54d
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 996eb0fd-712d-4c55-b1e1-c3fb6938ba86
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column IsYearStart
		dataType: int64
		formatString: 0
		lineageTag: 0fa01c5a-256d-4a9b-8846-df82a8e04316
		summarizeBy: sum
		sourceColumn: IsYearStart

		annotation SummarizationSetBy = Automatic

	column IsYearEnd
		dataType: int64
		formatString: 0
		lineageTag: e01fa196-d101-42f9-8ed9-a96013bf317d
		summarizeBy: sum
		sourceColumn: IsYearEnd

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 45ccab9c-ce97-43bf-8e64-e11a01b2663d
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c461ebcb-c06a-4fef-916a-e5bcb1fb8584
		summarizeBy: none
		sourceColumn: QuarterStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QuarterEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: dc499a69-273c-4b3b-a9b8-b0ba8bb8a289
		summarizeBy: none
		sourceColumn: QuarterEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsQuarterStart
		dataType: int64
		formatString: 0
		lineageTag: ccb9f3a0-81eb-4680-8416-4336a5807833
		summarizeBy: sum
		sourceColumn: IsQuarterStart

		annotation SummarizationSetBy = Automatic

	column IsQuarterEnd
		dataType: int64
		formatString: 0
		lineageTag: e42a4d4e-1e5a-46b3-98c2-594bc49b72f2
		summarizeBy: sum
		sourceColumn: IsQuarterEnd

		annotation SummarizationSetBy = Automatic

	column QuarterYear
		dataType: string
		lineageTag: 99dacc30-46c9-41cd-b8bc-02a7917d57b0
		summarizeBy: none
		sourceColumn: QuarterYear

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 5de2751c-c920-47e7-ad61-50362f65a8dd
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1c1b18b8-f048-48be-8ea1-4b1b458d11b5
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: 629c62a1-d4cf-47d5-ba88-01888209e775
		summarizeBy: none
		sourceColumn: MonthShort

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e1d2c99f-5076-4a6a-b114-ea862dbd50c8
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2453504c-d732-4600-a8e4-0519ce4281a9
		summarizeBy: none
		sourceColumn: MonthEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: dec1a8fb-1746-4776-8c7c-5e32a44bd907
		summarizeBy: none
		sourceColumn: MonthYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthYearNumber
		dataType: int64
		formatString: 0
		lineageTag: c2d4c82e-8707-4d57-8ddb-8f87e1074676
		summarizeBy: sum
		sourceColumn: MonthYearNumber

		annotation SummarizationSetBy = Automatic

	column CalendarMonthIndex
		dataType: int64
		formatString: 0
		lineageTag: 3a2407da-1f0a-490a-b6ec-cfa0af5c409d
		summarizeBy: sum
		sourceColumn: CalendarMonthIndex

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterIndex
		dataType: int64
		formatString: 0
		lineageTag: 569a30fa-6067-48fd-954c-2c2aa675e9e2
		summarizeBy: sum
		sourceColumn: CalendarQuarterIndex

		annotation SummarizationSetBy = Automatic

	column IsMonthStart
		dataType: int64
		formatString: 0
		lineageTag: 7ba9a583-cc65-49c4-bfae-4ef5cabe119d
		summarizeBy: sum
		sourceColumn: IsMonthStart

		annotation SummarizationSetBy = Automatic

	column IsMonthEnd
		dataType: int64
		formatString: 0
		lineageTag: c296b142-d065-41b6-be89-9b0ab2f75b51
		summarizeBy: sum
		sourceColumn: IsMonthEnd

		annotation SummarizationSetBy = Automatic

	column WeekOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 5427df1a-095d-45a6-b3a1-96273463af73
		summarizeBy: sum
		sourceColumn: WeekOfMonth

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 1a997df4-2abb-4de1-8d9d-8305dbd43ed1
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 79ec9d90-0bf8-455b-b330-6d5ef21a0ed3
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: efe73c27-c199-4ae3-b85c-e610acda1698
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column DayOfYear
		dataType: int64
		formatString: 0
		lineageTag: 1a8fe719-2776-4cef-8344-f4251db4e5fa
		summarizeBy: sum
		sourceColumn: DayOfYear

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 7d6e8180-ddfd-4ad8-bdb6-1f43015c81b3
		summarizeBy: sum
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: int64
		formatString: 0
		lineageTag: 4d167d05-7c47-44dd-bf28-0da4c96613b6
		summarizeBy: sum
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsBusinessDay
		dataType: int64
		formatString: 0
		lineageTag: 1f5ca372-3aa6-4b9a-b2a9-fb547bd03381
		summarizeBy: sum
		sourceColumn: IsBusinessDay

		annotation SummarizationSetBy = Automatic

	column NextBusinessDay
		dataType: dateTime
		formatString: Long Date
		lineageTag: 05d82fbc-a2c9-49a1-ac20-9079af2e0bc7
		summarizeBy: none
		sourceColumn: NextBusinessDay

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PreviousBusinessDay
		dataType: dateTime
		formatString: Long Date
		lineageTag: e3c83809-8168-44ff-8169-b9c8dd4e84f9
		summarizeBy: none
		sourceColumn: PreviousBusinessDay

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsToday
		dataType: int64
		formatString: 0
		lineageTag: 98462bd4-960c-46d6-8406-bf743cef09f9
		summarizeBy: sum
		sourceColumn: IsToday

		annotation SummarizationSetBy = Automatic

	column IsCurrentYear
		dataType: int64
		formatString: 0
		lineageTag: c2cba7b4-0a8f-47e5-a4dd-4c8e3c651b4b
		summarizeBy: sum
		sourceColumn: IsCurrentYear

		annotation SummarizationSetBy = Automatic

	column IsCurrentMonth
		dataType: int64
		formatString: 0
		lineageTag: 84c60459-6920-4c6a-aa08-c727841407ba
		summarizeBy: sum
		sourceColumn: IsCurrentMonth

		annotation SummarizationSetBy = Automatic

	column IsCurrentQuarter
		dataType: int64
		formatString: 0
		lineageTag: 4323b79a-710a-437c-a338-72047e9d261a
		summarizeBy: sum
		sourceColumn: IsCurrentQuarter

		annotation SummarizationSetBy = Automatic

	column CurrentDayOffset
		dataType: int64
		formatString: 0
		lineageTag: 59701842-1673-4a62-9f00-2dc46610c9d6
		summarizeBy: sum
		sourceColumn: CurrentDayOffset

		annotation SummarizationSetBy = Automatic

	column SequentialDayIndex
		dataType: int64
		formatString: 0
		lineageTag: 0bf07774-6920-4918-9934-834a9f937813
		summarizeBy: sum
		sourceColumn: SequentialDayIndex

		annotation SummarizationSetBy = Automatic

	column YearQuarterKey
		dataType: int64
		formatString: 0
		lineageTag: 771e290e-5d47-4f0c-b2bc-4e393e50ae6f
		summarizeBy: count
		sourceColumn: YearQuarterKey

		annotation SummarizationSetBy = Automatic

	column YearOffset
		dataType: int64
		formatString: 0
		lineageTag: 242c8837-97e8-4434-a2cb-33d9a80f4bf5
		summarizeBy: sum
		sourceColumn: YearOffset

		annotation SummarizationSetBy = Automatic

	column CalendarMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: 72d08d39-73b5-4677-9bc3-d27be5f89b41
		summarizeBy: sum
		sourceColumn: CalendarMonthOffset

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 06f4c3ec-25bb-4a6a-ad59-e678783f20d0
		summarizeBy: sum
		sourceColumn: CalendarQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FiscalYearStartYear
		dataType: int64
		formatString: 0
		lineageTag: 251f4104-3c58-4d58-8f37-4c64984ca124
		summarizeBy: sum
		sourceColumn: FiscalYearStartYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 3f67fbc3-ad3a-4976-a571-35b3b59f3b9b
		summarizeBy: sum
		sourceColumn: FiscalMonthNumber

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 2f3df150-e513-4f59-aa8e-4a7b196d360d
		summarizeBy: sum
		sourceColumn: FiscalQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FiscalMonthIndex
		dataType: int64
		formatString: 0
		lineageTag: c64abd32-0b8c-411e-8385-62d16d77761c
		summarizeBy: sum
		sourceColumn: FiscalMonthIndex

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterIndex
		dataType: int64
		formatString: 0
		lineageTag: cea3d19c-f298-45fd-95a3-1be7bfe19eea
		summarizeBy: sum
		sourceColumn: FiscalQuarterIndex

		annotation SummarizationSetBy = Automatic

	column FiscalMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: 19133e0f-d476-4d3b-9479-30a073a555b5
		summarizeBy: sum
		sourceColumn: FiscalMonthOffset

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 9c62448e-dd79-4202-b967-1963d03dab10
		summarizeBy: sum
		sourceColumn: FiscalQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterName
		dataType: string
		lineageTag: f7d2749d-476c-4b33-8e5d-9a584f3717b3
		summarizeBy: none
		sourceColumn: FiscalQuarterName

		annotation SummarizationSetBy = Automatic

	column FiscalYearBin
		dataType: string
		lineageTag: af665ca1-0937-497c-8b96-30a36e65c1a5
		summarizeBy: none
		sourceColumn: FiscalYearBin

		annotation SummarizationSetBy = Automatic

	column FiscalYearStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6caf8fb2-1f18-4a4f-89ac-4eb65857c4c3
		summarizeBy: none
		sourceColumn: FiscalYearStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalYearEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0ccc5387-9473-4199-9209-2880e8fc5f9e
		summarizeBy: none
		sourceColumn: FiscalYearEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalQuarterStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e672bcac-8125-48ba-8eb1-0dce34ef5f66
		summarizeBy: none
		sourceColumn: FiscalQuarterStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalQuarterEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5b1cd39e-6a1b-468d-a7a7-70e75e456a15
		summarizeBy: none
		sourceColumn: FiscalQuarterEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsFiscalYearStart
		dataType: int64
		formatString: 0
		lineageTag: 92de9431-4671-4348-9ea8-82e1a5034400
		summarizeBy: sum
		sourceColumn: IsFiscalYearStart

		annotation SummarizationSetBy = Automatic

	column IsFiscalYearEnd
		dataType: int64
		formatString: 0
		lineageTag: e52cc198-dcd6-4a24-ad3f-8007db7281ae
		summarizeBy: sum
		sourceColumn: IsFiscalYearEnd

		annotation SummarizationSetBy = Automatic

	column IsFiscalQuarterStart
		dataType: int64
		formatString: 0
		lineageTag: 0617bdc9-d1b3-4890-a53c-7058fb582848
		summarizeBy: sum
		sourceColumn: IsFiscalQuarterStart

		annotation SummarizationSetBy = Automatic

	column IsFiscalQuarterEnd
		dataType: int64
		formatString: 0
		lineageTag: 5ddfc881-cb68-498c-b2b9-7215d062edb5
		summarizeBy: sum
		sourceColumn: IsFiscalQuarterEnd

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: b29a5ec3-6782-410f-ac2e-856dbc350db6
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalYearLabel
		dataType: string
		lineageTag: b4275526-2e3b-4f08-94d9-1ea61000b33d
		summarizeBy: none
		sourceColumn: FiscalYearLabel

		annotation SummarizationSetBy = Automatic

	column FiscalSystem
		dataType: string
		lineageTag: 160b702c-1781-4124-8065-85219bded0d4
		summarizeBy: none
		sourceColumn: FiscalSystem

		annotation SummarizationSetBy = Automatic

	column WeeklyFiscalSystem
		dataType: string
		lineageTag: c9fb3b8f-286c-42c5-8431-e4fd7570a2cd
		summarizeBy: none
		sourceColumn: WeeklyFiscalSystem

		annotation SummarizationSetBy = Automatic

	column FWYearNumber
		dataType: int64
		formatString: 0
		lineageTag: c4fdc647-51dc-43bc-bbe1-cf9d05ea6885
		summarizeBy: sum
		sourceColumn: FWYearNumber

		annotation SummarizationSetBy = Automatic

	column FWYearLabel
		dataType: string
		lineageTag: 978b4866-ce70-4b16-8cdc-25de1c1ec47e
		summarizeBy: none
		sourceColumn: FWYearLabel

		annotation SummarizationSetBy = Automatic

	column FWQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 2502e397-8208-4423-b39e-6b006590d649
		summarizeBy: sum
		sourceColumn: FWQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWQuarterLabel
		dataType: string
		lineageTag: 7162f580-016f-422c-b19f-9377a46efd38
		summarizeBy: none
		sourceColumn: FWQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FWYearQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 1f5889cf-a187-497b-a957-5b1ecbaed326
		summarizeBy: sum
		sourceColumn: FWYearQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWYearQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 05d64fea-3eae-4ab8-871b-777d570fee7f
		summarizeBy: sum
		sourceColumn: FWYearQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FWMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: fd410141-2c42-4987-9b0c-cd168e0abb06
		summarizeBy: sum
		sourceColumn: FWMonthNumber

		annotation SummarizationSetBy = Automatic

	column FWMonthLabel
		dataType: string
		lineageTag: 45a031fb-6ad7-4846-8a9e-5b49fa3c4c74
		summarizeBy: none
		sourceColumn: FWMonthLabel

		annotation SummarizationSetBy = Automatic

	column FWYearMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 73fbc2f8-9ba5-41ca-a57e-489cd92faaf0
		summarizeBy: sum
		sourceColumn: FWYearMonthNumber

		annotation SummarizationSetBy = Automatic

	column FWYearMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: 23935070-ffc1-453f-9df3-40640b786501
		summarizeBy: sum
		sourceColumn: FWYearMonthOffset

		annotation SummarizationSetBy = Automatic

	column FWWeekNumber
		dataType: int64
		formatString: 0
		lineageTag: 52aba8a4-3874-47e0-b258-88de9d1a2f69
		summarizeBy: sum
		sourceColumn: FWWeekNumber

		annotation SummarizationSetBy = Automatic

	column FWWeekLabel
		dataType: string
		lineageTag: b613b39c-6807-4632-affc-94684fb23961
		summarizeBy: none
		sourceColumn: FWWeekLabel

		annotation SummarizationSetBy = Automatic

	column FWYearWeekNumber
		dataType: int64
		formatString: 0
		lineageTag: b81de9e3-132b-49c9-9d67-1ea36c5cd914
		summarizeBy: sum
		sourceColumn: FWYearWeekNumber

		annotation SummarizationSetBy = Automatic

	column FWYearWeekOffset
		dataType: int64
		formatString: 0
		lineageTag: 525e3c95-558d-4a3a-b102-32886b838ca6
		summarizeBy: sum
		sourceColumn: FWYearWeekOffset

		annotation SummarizationSetBy = Automatic

	column FWPeriodNumber
		dataType: int64
		formatString: 0
		lineageTag: 02ebd27e-7973-41e2-94ba-fb50f466b8e8
		summarizeBy: sum
		sourceColumn: FWPeriodNumber

		annotation SummarizationSetBy = Automatic

	column FWPeriodLabel
		dataType: string
		lineageTag: 608a1b71-a371-4b50-abbe-544dd9f3bf14
		summarizeBy: none
		sourceColumn: FWPeriodLabel

		annotation SummarizationSetBy = Automatic

	column FWStartOfYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9510dc04-2194-4f46-b115-f2d5742c6b1c
		summarizeBy: none
		sourceColumn: FWStartOfYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: e933869d-af5c-4ffa-b846-91919edc488b
		summarizeBy: none
		sourceColumn: FWEndOfYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWStartOfQuarter
		dataType: dateTime
		formatString: Long Date
		lineageTag: fb8696a3-737d-4532-a318-21e68bde624d
		summarizeBy: none
		sourceColumn: FWStartOfQuarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfQuarter
		dataType: dateTime
		formatString: Long Date
		lineageTag: 75618d53-c0e9-4c91-99e3-b17ac31fb3b1
		summarizeBy: none
		sourceColumn: FWEndOfQuarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWStartOfMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: a98f6d59-5ad9-4333-85fb-97256d733313
		summarizeBy: none
		sourceColumn: FWStartOfMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: df5b331b-bfb1-4aac-ace3-276a23270e10
		summarizeBy: none
		sourceColumn: FWEndOfMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWStartOfWeek
		dataType: dateTime
		formatString: Long Date
		lineageTag: c648b729-fb18-4248-9c98-bcd5fd620805
		summarizeBy: none
		sourceColumn: FWStartOfWeek

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfWeek
		dataType: dateTime
		formatString: Long Date
		lineageTag: 99dedc9d-01ec-4876-85a6-5637a61903c1
		summarizeBy: none
		sourceColumn: FWEndOfWeek

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekDayNumber
		dataType: int64
		formatString: 0
		lineageTag: a3ea94fc-53fa-485b-aece-edfa6ea81f02
		summarizeBy: sum
		sourceColumn: WeekDayNumber

		annotation SummarizationSetBy = Automatic

	column WeekDayNameShort
		dataType: string
		lineageTag: 0bc15397-ed5d-4d6e-9ada-1e3a6f78f585
		summarizeBy: none
		sourceColumn: WeekDayNameShort

		annotation SummarizationSetBy = Automatic

	column FWDayOfYearNumber
		dataType: int64
		formatString: 0
		lineageTag: 80ae69aa-7a7b-4e5c-823b-a9adf006c2f8
		summarizeBy: sum
		sourceColumn: FWDayOfYearNumber

		annotation SummarizationSetBy = Automatic

	column FWDayOfQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 097403bc-fa67-4850-aebe-600d3cacc60e
		summarizeBy: sum
		sourceColumn: FWDayOfQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWDayOfMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: cc267f54-0f7d-400c-9ddd-683de3472a9b
		summarizeBy: sum
		sourceColumn: FWDayOfMonthNumber

		annotation SummarizationSetBy = Automatic

	column IsWorkingDay
		dataType: int64
		formatString: 0
		lineageTag: 18c37657-ade9-473f-bf50-c66ca258e41c
		summarizeBy: sum
		sourceColumn: IsWorkingDay

		annotation SummarizationSetBy = Automatic

	column DayType
		dataType: string
		lineageTag: 429c6d1d-e80e-45b5-b89e-4060a581c064
		summarizeBy: none
		sourceColumn: DayType

		annotation SummarizationSetBy = Automatic

	column FWWeekInQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 0e99eb5d-9072-4fe9-94fa-0b8eeab9690b
		summarizeBy: sum
		sourceColumn: FWWeekInQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWYearMonthLabel
		dataType: string
		lineageTag: 7530d4d8-edd9-4022-ae97-bd04b08f18dc
		summarizeBy: none
		sourceColumn: FWYearMonthLabel

		annotation SummarizationSetBy = Automatic

	partition Dates = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "dates" ),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type date}, {"DateKey", Int64.Type}, {"SequentialDayIndex", Int64.Type}, {"Year", Int64.Type}, {"Quarter", Int64.Type}, {"QuarterStartDate", type date}, {"QuarterEndDate", type date}, {"QuarterYear", type text}, {"Month", Int64.Type}, {"MonthName", type text}, {"MonthShort", type text}, {"MonthStartDate", type date}, {"MonthEndDate", type date}, {"MonthYear", type date}, {"MonthYearNumber", Int64.Type}, {"YearQuarterKey", Int64.Type}, {"CalendarMonthIndex", Int64.Type}, {"CalendarQuarterIndex", Int64.Type}, {"WeekOfMonth", Int64.Type}, {"Day", Int64.Type}, {"DayName", type text}, {"DayShort", type text}, {"DayOfYear", Int64.Type}, {"DayOfWeek", Int64.Type}, {"IsWeekend", Int64.Type}, {"IsBusinessDay", Int64.Type}, {"NextBusinessDay", type date}, {"PreviousBusinessDay", type date}, {"IsYearStart", Int64.Type}, {"IsYearEnd", Int64.Type}, {"IsQuarterStart", Int64.Type}, {"IsQuarterEnd", Int64.Type}, {"IsMonthStart", Int64.Type}, {"IsMonthEnd", Int64.Type}, {"IsToday", Int64.Type}, {"IsCurrentYear", Int64.Type}, {"IsCurrentMonth", Int64.Type}, {"IsCurrentQuarter", Int64.Type}, {"CurrentDayOffset", Int64.Type}, {"YearOffset", Int64.Type}, {"CalendarMonthOffset", Int64.Type}, {"CalendarQuarterOffset", Int64.Type}, {"FiscalYearStartYear", Int64.Type}, {"FiscalMonthNumber", Int64.Type}, {"FiscalQuarterNumber", Int64.Type}, {"FiscalMonthIndex", Int64.Type}, {"FiscalQuarterIndex", Int64.Type}, {"FiscalMonthOffset", Int64.Type}, {"FiscalQuarterOffset", Int64.Type}, {"FiscalQuarterName", type text}, {"FiscalYearBin", type text}, {"FiscalYearStartDate", type date}, {"FiscalYearEndDate", type date}, {"FiscalQuarterStartDate", type date}, {"FiscalQuarterEndDate", type date}, {"IsFiscalYearStart", Int64.Type}, {"IsFiscalYearEnd", Int64.Type}, {"IsFiscalQuarterStart", Int64.Type}, {"IsFiscalQuarterEnd", Int64.Type}, {"FiscalYear", Int64.Type}, {"FiscalYearLabel", type text}, {"FiscalSystem", type text}, {"WeeklyFiscalSystem", type text}, {"FWYearNumber", Int64.Type}, {"FWYearLabel", type text}, {"FWQuarterNumber", Int64.Type}, {"FWQuarterLabel", type text}, {"FWYearQuarterNumber", Int64.Type}, {"FWYearQuarterOffset", Int64.Type}, {"FWMonthNumber", Int64.Type}, {"FWMonthLabel", type text}, {"FWYearMonthNumber", Int64.Type}, {"FWYearMonthOffset", Int64.Type}, {"FWWeekNumber", Int64.Type}, {"FWWeekLabel", type text}, {"FWYearWeekNumber", Int64.Type}, {"FWYearWeekOffset", Int64.Type}, {"FWPeriodNumber", Int64.Type}, {"FWPeriodLabel", type text}, {"FWStartOfYear", type date}, {"FWEndOfYear", type date}, {"FWStartOfQuarter", type date}, {"FWEndOfQuarter", type date}, {"FWStartOfMonth", type date}, {"FWEndOfMonth", type date}, {"FWStartOfWeek", type date}, {"FWEndOfWeek", type date}, {"WeekDayNumber", Int64.Type}, {"WeekDayNameShort", type text}, {"FWDayOfYearNumber", Int64.Type}, {"FWDayOfQuarterNumber", Int64.Type}, {"FWDayOfMonthNumber", Int64.Type}, {"IsWorkingDay", Int64.Type}, {"DayType", type text}, {"FWWeekInQuarterNumber", Int64.Type}, {"FWYearMonthLabel", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

