table Products
	lineageTag: a736d030-7050-4b89-afb0-103296247af9

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 817fb5b9-efba-4622-9733-06c52a3785e4
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductCode
		dataType: int64
		formatString: 0
		lineageTag: 361f0e4b-eb23-4937-8dac-22a201b28459
		summarizeBy: count
		sourceColumn: ProductCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 22321e1c-f522-4b5f-874e-aa5d32b76c35
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ProductDescription
		dataType: string
		lineageTag: 15e4db0b-ef90-4c66-88a9-8b3b8b5e6396
		summarizeBy: none
		sourceColumn: ProductDescription

		annotation SummarizationSetBy = Automatic

	column SubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 169bba0b-83a5-49c2-ae55-f76e8d03183f
		summarizeBy: count
		sourceColumn: SubcategoryKey

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: a2dc35fb-6ee5-4ff5-9adf-abc288b1c3ef
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Class
		dataType: string
		lineageTag: 589d9b5a-c66d-4b43-80bd-0538d5efe4a7
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 6ee81513-8370-473a-8cca-279477f735db
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column StockTypeCode
		dataType: int64
		formatString: 0
		lineageTag: 29179efc-8bbc-464f-a2ec-9dc6e80bc4a8
		summarizeBy: count
		sourceColumn: StockTypeCode

		annotation SummarizationSetBy = Automatic

	column StockType
		dataType: string
		lineageTag: 74663ff5-bf7e-41b9-b2de-5187e17f5f63
		summarizeBy: none
		sourceColumn: StockType

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: int64
		formatString: #,0.00
		lineageTag: 55417800-0963-4dcf-bbb2-b6a61d0f428a
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		formatString: #,0.00
		lineageTag: 11e753c5-0f96-43ea-83b7-a269d2c1a0d6
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column BaseProductKey
		dataType: int64
		formatString: 0
		lineageTag: e1219f43-3c77-47eb-8654-8da6b4a5df26
		summarizeBy: count
		sourceColumn: BaseProductKey

		annotation SummarizationSetBy = Automatic

	column VariantIndex
		dataType: int64
		formatString: 0
		lineageTag: 849c6ce3-9802-4902-a69f-56f08d095ce9
		summarizeBy: sum
		sourceColumn: VariantIndex

		annotation SummarizationSetBy = Automatic

	column IsActiveInSales
		dataType: int64
		formatString: 0
		lineageTag: 8c492ffd-f8ae-4dda-86fe-9a9c21684a60
		summarizeBy: sum
		sourceColumn: IsActiveInSales

		annotation SummarizationSetBy = Automatic

	column LaunchDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 559e51a1-ec68-486f-bef2-780b1461588e
		summarizeBy: none
		sourceColumn: LaunchDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LaunchDateKey
		dataType: int64
		formatString: 0
		lineageTag: 3fb7933d-1c51-4905-9e8a-318ba0217eb0
		summarizeBy: count
		sourceColumn: LaunchDateKey

		annotation SummarizationSetBy = Automatic

	column DiscontinuedDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 113e6429-19ba-47a7-a63e-8f487145e6d6
		summarizeBy: none
		sourceColumn: DiscontinuedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DiscontinuedDateKey
		dataType: int64
		formatString: 0
		lineageTag: 6d3eb993-e53b-4802-9cca-74aa873c0a18
		summarizeBy: count
		sourceColumn: DiscontinuedDateKey

		annotation SummarizationSetBy = Automatic

	column IsDiscontinued
		dataType: int64
		formatString: 0
		lineageTag: 83ed61cd-22e5-4bf4-b3eb-f81ea68722a5
		summarizeBy: sum
		sourceColumn: IsDiscontinued

		annotation SummarizationSetBy = Automatic

	column ColorFamily
		dataType: string
		lineageTag: 5f6ed0bc-82ca-4871-b2cf-b3d9b27f20d2
		summarizeBy: none
		sourceColumn: ColorFamily

		annotation SummarizationSetBy = Automatic

	column Material
		dataType: string
		lineageTag: ca521b03-a0ba-4694-bb4c-2107441fc758
		summarizeBy: none
		sourceColumn: Material

		annotation SummarizationSetBy = Automatic

	column Style
		dataType: string
		lineageTag: f128ba78-f521-49da-a986-83aa5156f6e4
		summarizeBy: none
		sourceColumn: Style

		annotation SummarizationSetBy = Automatic

	column AgeGroup
		dataType: string
		lineageTag: 6603c052-2650-4bc8-92ae-8f1b15023a05
		summarizeBy: none
		sourceColumn: AgeGroup

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: 8c275c2e-ffb2-48dd-9fa9-00af8cb8d138
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column SeasonalityProfile
		dataType: string
		lineageTag: 5e63e4fb-188c-4cdc-b910-de579c71402d
		summarizeBy: none
		sourceColumn: SeasonalityProfile

		annotation SummarizationSetBy = Automatic

	column WeightKg
		dataType: double
		lineageTag: c3168360-8b7b-4a01-bb73-56cad0d646e6
		summarizeBy: sum
		sourceColumn: WeightKg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LengthCm
		dataType: double
		lineageTag: f1a9ecaa-df57-44f5-8447-075b797d32c9
		summarizeBy: sum
		sourceColumn: LengthCm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WidthCm
		dataType: double
		lineageTag: 0edf9409-f2c0-44c8-a5fb-7b8ed3a1ea10
		summarizeBy: sum
		sourceColumn: WidthCm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HeightCm
		dataType: double
		lineageTag: 5b0fef1f-8a61-410c-b6f3-a2ef947a5b46
		summarizeBy: sum
		sourceColumn: HeightCm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VolumeCm3
		dataType: double
		lineageTag: 41b77793-ef19-42b0-a422-ad09d89313a3
		summarizeBy: sum
		sourceColumn: VolumeCm3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShippingClass
		dataType: string
		lineageTag: 3698da63-13a1-42b2-8603-cbdca3ab6835
		summarizeBy: none
		sourceColumn: ShippingClass

		annotation SummarizationSetBy = Automatic

	column IsFragile
		dataType: int64
		formatString: 0
		lineageTag: 3219e266-51fd-4aa7-a236-6b4fc27089a4
		summarizeBy: sum
		sourceColumn: IsFragile

		annotation SummarizationSetBy = Automatic

	column IsHazmat
		dataType: int64
		formatString: 0
		lineageTag: 26c07d57-d358-4252-8214-efbaa2ea4c74
		summarizeBy: sum
		sourceColumn: IsHazmat

		annotation SummarizationSetBy = Automatic

	column LeadTimeDays
		dataType: int64
		formatString: 0
		lineageTag: c00f4c75-0805-4eda-bd4d-f68533a2bbb1
		summarizeBy: sum
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column CasePackQty
		dataType: int64
		formatString: 0
		lineageTag: 0995e789-8e7a-4e3a-8c11-ac58f4bc8cdf
		summarizeBy: sum
		sourceColumn: CasePackQty

		annotation SummarizationSetBy = Automatic

	column FulfillmentType
		dataType: string
		lineageTag: a4861ebf-b9e4-43df-ba05-94d09c5c1b21
		summarizeBy: none
		sourceColumn: FulfillmentType

		annotation SummarizationSetBy = Automatic

	column BrandTier
		dataType: string
		lineageTag: 6755e339-387e-46fb-8b21-f8c7d4044331
		summarizeBy: none
		sourceColumn: BrandTier

		annotation SummarizationSetBy = Automatic

	column EligibleStore
		dataType: int64
		formatString: 0
		lineageTag: f8113bbf-a8ca-4a82-be9a-9d8971f4b9a9
		summarizeBy: sum
		sourceColumn: EligibleStore

		annotation SummarizationSetBy = Automatic

	column EligibleOnline
		dataType: int64
		formatString: 0
		lineageTag: 4ae18c7f-f925-4e98-b3f4-eff8f1cbd32a
		summarizeBy: sum
		sourceColumn: EligibleOnline

		annotation SummarizationSetBy = Automatic

	column EligibleMarketplace
		dataType: int64
		formatString: 0
		lineageTag: 305526ca-851b-4451-8210-7c410e465385
		summarizeBy: sum
		sourceColumn: EligibleMarketplace

		annotation SummarizationSetBy = Automatic

	column EligibleB2B
		dataType: int64
		formatString: 0
		lineageTag: 9f8dbd3f-0ed1-4551-accd-dcafcab8c876
		summarizeBy: sum
		sourceColumn: EligibleB2B

		annotation SummarizationSetBy = Automatic

	column WarrantyMonths
		dataType: int64
		formatString: 0
		lineageTag: 8775497a-11f1-4013-a1c6-a91c4ca424cc
		summarizeBy: sum
		sourceColumn: WarrantyMonths

		annotation SummarizationSetBy = Automatic

	column ReturnRateBase
		dataType: double
		lineageTag: f5d04211-d1cb-40b0-8c4c-9443c0c9a81f
		summarizeBy: sum
		sourceColumn: ReturnRateBase

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DefectRateBase
		dataType: double
		lineageTag: ce14e0b7-a30f-4a77-ab5a-2ca581644500
		summarizeBy: sum
		sourceColumn: DefectRateBase

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ReturnWindowDays
		dataType: int64
		formatString: 0
		lineageTag: c20e6527-8823-42a9-b4e0-3fbec0931f95
		summarizeBy: sum
		sourceColumn: ReturnWindowDays

		annotation SummarizationSetBy = Automatic

	column SupplierKey
		dataType: int64
		formatString: 0
		lineageTag: cec89e20-f221-46d6-9de3-2593410fd485
		summarizeBy: count
		sourceColumn: SupplierKey

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "products" ),
				    ChangedType = Table.TransformColumnTypes (
				        Source,
				        {
				            { "ProductKey", Int64.Type },
				            { "ProductCode", Int64.Type },
				            { "ProductName", type text },
				            { "ProductDescription", type text },
				            { "SubcategoryKey", Int64.Type },
				            { "Brand", type text },
				            { "Class", type text },
				            { "Color", type text },
				            { "StockTypeCode", Int64.Type },
				            { "StockType", type text },
				            { "UnitCost", Int64.Type },
				            { "UnitPrice", type number },
				            { "BaseProductKey", Int64.Type },
				            { "VariantIndex", Int64.Type },
				            { "LaunchDate", type date },
				            { "LaunchDateKey", Int64.Type },
				            { "DiscontinuedDate", type date },
				            { "DiscontinuedDateKey", Int64.Type },
				            { "IsDiscontinued", Int64.Type },
				            { "ColorFamily", type text },
				            { "Material", type text },
				            { "Style", type text },
				            { "AgeGroup", type text },
				            { "ProductLine", type text },
				            { "SeasonalityProfile", type text },
				            { "WeightKg", type number },
				            { "LengthCm", type number },
				            { "WidthCm", type number },
				            { "HeightCm", type number },
				            { "VolumeCm3", type number },
				            { "ShippingClass", type text },
				            { "IsFragile", Int64.Type },
				            { "IsHazmat", Int64.Type },
				            { "LeadTimeDays", Int64.Type },
				            { "CasePackQty", Int64.Type },
				            { "FulfillmentType", type text },
				            { "BrandTier", type text },
				            { "EligibleStore", Int64.Type },
				            { "EligibleOnline", Int64.Type },
				            { "EligibleMarketplace", Int64.Type },
				            { "EligibleB2B", Int64.Type },
				            { "WarrantyMonths", Int64.Type },
				            { "ReturnRateBase", type number },
				            { "DefectRateBase", type number },
				            { "ReturnWindowDays", Int64.Type },
				            { "SupplierKey", Int64.Type },
				            { "IsActiveInSales", Int64.Type }
				        }
				    )
				in
				    ChangedType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

