table Products
	lineageTag: a736d030-7050-4b89-afb0-103296247af9

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 817fb5b9-efba-4622-9733-06c52a3785e4
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductCode
		dataType: int64
		formatString: 0
		lineageTag: 361f0e4b-eb23-4937-8dac-22a201b28459
		summarizeBy: count
		sourceColumn: ProductCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 22321e1c-f522-4b5f-874e-aa5d32b76c35
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ProductDescription
		dataType: string
		lineageTag: 15e4db0b-ef90-4c66-88a9-8b3b8b5e6396
		summarizeBy: none
		sourceColumn: ProductDescription

		annotation SummarizationSetBy = Automatic

	column SubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 169bba0b-83a5-49c2-ae55-f76e8d03183f
		summarizeBy: count
		sourceColumn: SubcategoryKey

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: a2dc35fb-6ee5-4ff5-9adf-abc288b1c3ef
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Class
		dataType: string
		lineageTag: 589d9b5a-c66d-4b43-80bd-0538d5efe4a7
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 6ee81513-8370-473a-8cca-279477f735db
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column StockTypeCode
		dataType: int64
		formatString: 0
		lineageTag: 29179efc-8bbc-464f-a2ec-9dc6e80bc4a8
		summarizeBy: count
		sourceColumn: StockTypeCode

		annotation SummarizationSetBy = Automatic

	column StockType
		dataType: string
		lineageTag: 74663ff5-bf7e-41b9-b2de-5187e17f5f63
		summarizeBy: none
		sourceColumn: StockType

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		formatString: #,0.00
		lineageTag: 55417800-0963-4dcf-bbb2-b6a61d0f428a
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

	column BaseProductKey
		dataType: int64
		formatString: 0
		lineageTag: e1219f43-3c77-47eb-8654-8da6b4a5df26
		summarizeBy: count
		sourceColumn: BaseProductKey

		annotation SummarizationSetBy = Automatic

	column VariantIndex
		dataType: int64
		formatString: 0
		lineageTag: 849c6ce3-9802-4902-a69f-56f08d095ce9
		summarizeBy: sum
		sourceColumn: VariantIndex

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: efab0543-e5e3-4a5d-9fed-fef38db1f906
		summarizeBy: count
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column VersionNumber
		dataType: int64
		formatString: 0
		lineageTag: 435bbdd8-274e-4136-a290-1ee5d0b7cac5
		summarizeBy: sum
		sourceColumn: VersionNumber

		annotation SummarizationSetBy = Automatic

	column EffectiveStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e9364e61-ef5d-4a7c-b8b5-e51fa2de3203
		summarizeBy: none
		sourceColumn: EffectiveStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EffectiveEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5963f915-690f-4c05-8f0c-81d85d4e372a
		summarizeBy: none
		sourceColumn: EffectiveEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsCurrent
		dataType: int64
		formatString: 0
		lineageTag: f413e97b-5856-4044-bf39-31e43c112e5d
		summarizeBy: sum
		sourceColumn: IsCurrent

		annotation SummarizationSetBy = Automatic

	column ListPrice
		dataType: double
		lineageTag: e82ca91c-e695-479c-ba65-936bdaf47bc5
		summarizeBy: sum
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Source
		dataType: string
		lineageTag: 5c2afb31-2769-41d8-89ad-e873318007e9
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		queryGroup: Dimensions\Products
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "products" ),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ProductKey", Int64.Type}, {"ProductID", Int64.Type}, {"VersionNumber", Int64.Type}, {"EffectiveStartDate", type date}, {"EffectiveEndDate", type date}, {"IsCurrent", Int64.Type}, {"ProductCode", Int64.Type}, {"ProductName", type text}, {"ProductDescription", type text}, {"SubcategoryKey", Int64.Type}, {"Brand", type text}, {"Class", type text}, {"Color", type text}, {"StockTypeCode", Int64.Type}, {"StockType", type text}, {"UnitCost", type number}, {"ListPrice", type number}, {"BaseProductKey", Int64.Type}, {"VariantIndex", Int64.Type}, {"Source", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

