table SalesReturns
	lineageTag: 9898b162-1a5a-4975-b5c3-f5d0b4a062f9

	column SalesOrderNumber
		dataType: int64
		formatString: 0
		lineageTag: f716a86b-63c9-41e3-9d65-3ff48cd380aa
		summarizeBy: sum
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: ee3b718a-109c-4340-8c1e-8111f9d2dbf1
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column ReturnDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: ee1fda21-4916-4536-8a1d-9391b130cd50
		summarizeBy: none
		sourceColumn: ReturnDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ReturnReasonKey
		dataType: int64
		formatString: 0
		lineageTag: c14a824f-5101-48f9-bc47-0d8342d891b4
		summarizeBy: count
		sourceColumn: ReturnReasonKey

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: 28b95e13-448e-4f2b-84a6-7c71b11cee42
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	column ReturnNetPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8ba4d7a8-2b0c-49d2-83e9-025d014bcbb4
		summarizeBy: sum
		sourceColumn: ReturnNetPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ReturnEventKey
		dataType: int64
		formatString: 0
		lineageTag: 4f8fe63a-f755-4723-9443-aef5bb80ac3a
		summarizeBy: count
		sourceColumn: ReturnEventKey

		annotation SummarizationSetBy = Automatic

	partition SalesReturns = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = Folder.Files ( ContosoFolder & "\facts\sales_return" ),
				    RemoveCols = Table.SelectColumns ( Source, { "Content" } ),
				    RemoveHidden = Table.SelectRows ( RemoveCols, each [Attributes]?[Hidden]? <> true ),
				    InvokeCustom = Table.AddColumn (
				        RemoveHidden,
				        "Transform File",
				        each Transform_SalesReturns_File ( [Content] )
				    ),
				    RemoveOtherCol = Table.SelectColumns ( InvokeCustom, { "Transform File" } ),
				    CombineTables = Table.ExpandTableColumn (
				        RemoveOtherCol,
				        "Transform File",
				        Table.ColumnNames ( Transform_SalesReturns_File ( Sample_File_SalesReturns ) )
				    ),
				    ChangeType = Table.TransformColumnTypes (
				        CombineTables,
				        {
				            { "SalesOrderNumber", Int64.Type },
				            { "SalesOrderLineNumber", Int64.Type },
				            { "ReturnDate", type date },
				            { "ReturnReasonKey", Int64.Type },
				            { "ReturnQuantity", Int64.Type },
				            { "ReturnNetPrice", Currency.Type },
				            { "ReturnEventKey", Int64.Type }
				        }
				    )
				in
				    ChangeType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

