table Dates
	lineageTag: 1e93e289-4d40-485f-9fbc-7760c3c5e1fd
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 3fd4def5-f7ac-43bb-b84a-3bab249d71e1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 39c1bef1-cb8a-4c3f-8251-70835117b54d
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 996eb0fd-712d-4c55-b1e1-c3fb6938ba86
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column IsYearStart
		dataType: int64
		formatString: 0
		lineageTag: 0fa01c5a-256d-4a9b-8846-df82a8e04316
		summarizeBy: sum
		sourceColumn: IsYearStart

		annotation SummarizationSetBy = Automatic

	column IsYearEnd
		dataType: int64
		formatString: 0
		lineageTag: e01fa196-d101-42f9-8ed9-a96013bf317d
		summarizeBy: sum
		sourceColumn: IsYearEnd

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 45ccab9c-ce97-43bf-8e64-e11a01b2663d
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c461ebcb-c06a-4fef-916a-e5bcb1fb8584
		summarizeBy: none
		sourceColumn: QuarterStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QuarterEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: dc499a69-273c-4b3b-a9b8-b0ba8bb8a289
		summarizeBy: none
		sourceColumn: QuarterEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsQuarterStart
		dataType: int64
		formatString: 0
		lineageTag: ccb9f3a0-81eb-4680-8416-4336a5807833
		summarizeBy: sum
		sourceColumn: IsQuarterStart

		annotation SummarizationSetBy = Automatic

	column IsQuarterEnd
		dataType: int64
		formatString: 0
		lineageTag: e42a4d4e-1e5a-46b3-98c2-594bc49b72f2
		summarizeBy: sum
		sourceColumn: IsQuarterEnd

		annotation SummarizationSetBy = Automatic

	column QuarterYear
		dataType: string
		lineageTag: 99dacc30-46c9-41cd-b8bc-02a7917d57b0
		summarizeBy: none
		sourceColumn: QuarterYear

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 5de2751c-c920-47e7-ad61-50362f65a8dd
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 1c1b18b8-f048-48be-8ea1-4b1b458d11b5
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: 629c62a1-d4cf-47d5-ba88-01888209e775
		summarizeBy: none
		sourceColumn: MonthShort

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e1d2c99f-5076-4a6a-b114-ea862dbd50c8
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2453504c-d732-4600-a8e4-0519ce4281a9
		summarizeBy: none
		sourceColumn: MonthEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: dec1a8fb-1746-4776-8c7c-5e32a44bd907
		summarizeBy: none
		sourceColumn: MonthYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthYearNumber
		dataType: int64
		formatString: 0
		lineageTag: c2d4c82e-8707-4d57-8ddb-8f87e1074676
		summarizeBy: sum
		sourceColumn: MonthYearNumber

		annotation SummarizationSetBy = Automatic

	column CalendarMonthIndex
		dataType: int64
		formatString: 0
		lineageTag: 3a2407da-1f0a-490a-b6ec-cfa0af5c409d
		summarizeBy: sum
		sourceColumn: CalendarMonthIndex

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterIndex
		dataType: int64
		formatString: 0
		lineageTag: 569a30fa-6067-48fd-954c-2c2aa675e9e2
		summarizeBy: sum
		sourceColumn: CalendarQuarterIndex

		annotation SummarizationSetBy = Automatic

	column IsMonthStart
		dataType: int64
		formatString: 0
		lineageTag: 7ba9a583-cc65-49c4-bfae-4ef5cabe119d
		summarizeBy: sum
		sourceColumn: IsMonthStart

		annotation SummarizationSetBy = Automatic

	column IsMonthEnd
		dataType: int64
		formatString: 0
		lineageTag: c296b142-d065-41b6-be89-9b0ab2f75b51
		summarizeBy: sum
		sourceColumn: IsMonthEnd

		annotation SummarizationSetBy = Automatic

	column WeekOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 5427df1a-095d-45a6-b3a1-96273463af73
		summarizeBy: sum
		sourceColumn: WeekOfMonth

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 1a997df4-2abb-4de1-8d9d-8305dbd43ed1
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 79ec9d90-0bf8-455b-b330-6d5ef21a0ed3
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: efe73c27-c199-4ae3-b85c-e610acda1698
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column DayOfYear
		dataType: int64
		formatString: 0
		lineageTag: 1a8fe719-2776-4cef-8344-f4251db4e5fa
		summarizeBy: sum
		sourceColumn: DayOfYear

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 7d6e8180-ddfd-4ad8-bdb6-1f43015c81b3
		summarizeBy: sum
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: int64
		formatString: 0
		lineageTag: 4d167d05-7c47-44dd-bf28-0da4c96613b6
		summarizeBy: sum
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsBusinessDay
		dataType: int64
		formatString: 0
		lineageTag: 1f5ca372-3aa6-4b9a-b2a9-fb547bd03381
		summarizeBy: sum
		sourceColumn: IsBusinessDay

		annotation SummarizationSetBy = Automatic

	column NextBusinessDay
		dataType: dateTime
		formatString: Long Date
		lineageTag: 05d82fbc-a2c9-49a1-ac20-9079af2e0bc7
		summarizeBy: none
		sourceColumn: NextBusinessDay

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PreviousBusinessDay
		dataType: dateTime
		formatString: Long Date
		lineageTag: e3c83809-8168-44ff-8169-b9c8dd4e84f9
		summarizeBy: none
		sourceColumn: PreviousBusinessDay

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsToday
		dataType: int64
		formatString: 0
		lineageTag: 98462bd4-960c-46d6-8406-bf743cef09f9
		summarizeBy: sum
		sourceColumn: IsToday

		annotation SummarizationSetBy = Automatic

	column IsCurrentYear
		dataType: int64
		formatString: 0
		lineageTag: c2cba7b4-0a8f-47e5-a4dd-4c8e3c651b4b
		summarizeBy: sum
		sourceColumn: IsCurrentYear

		annotation SummarizationSetBy = Automatic

	column IsCurrentMonth
		dataType: int64
		formatString: 0
		lineageTag: 84c60459-6920-4c6a-aa08-c727841407ba
		summarizeBy: sum
		sourceColumn: IsCurrentMonth

		annotation SummarizationSetBy = Automatic

	column IsCurrentQuarter
		dataType: int64
		formatString: 0
		lineageTag: 4323b79a-710a-437c-a338-72047e9d261a
		summarizeBy: sum
		sourceColumn: IsCurrentQuarter

		annotation SummarizationSetBy = Automatic

	column CurrentDayOffset
		dataType: int64
		formatString: 0
		lineageTag: 59701842-1673-4a62-9f00-2dc46610c9d6
		summarizeBy: sum
		sourceColumn: CurrentDayOffset

		annotation SummarizationSetBy = Automatic

	column SequentialDayIndex
		dataType: int64
		formatString: 0
		lineageTag: 0bf07774-6920-4918-9934-834a9f937813
		summarizeBy: sum
		sourceColumn: SequentialDayIndex

		annotation SummarizationSetBy = Automatic

	column YearQuarterKey
		dataType: int64
		formatString: 0
		lineageTag: 771e290e-5d47-4f0c-b2bc-4e393e50ae6f
		summarizeBy: count
		sourceColumn: YearQuarterKey

		annotation SummarizationSetBy = Automatic

	column YearOffset
		dataType: int64
		formatString: 0
		lineageTag: 242c8837-97e8-4434-a2cb-33d9a80f4bf5
		summarizeBy: sum
		sourceColumn: YearOffset

		annotation SummarizationSetBy = Automatic

	column CalendarMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: 72d08d39-73b5-4677-9bc3-d27be5f89b41
		summarizeBy: sum
		sourceColumn: CalendarMonthOffset

		annotation SummarizationSetBy = Automatic

	column CalendarQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 06f4c3ec-25bb-4a6a-ad59-e678783f20d0
		summarizeBy: sum
		sourceColumn: CalendarQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FiscalYearStartYear
		dataType: int64
		formatString: 0
		lineageTag: eac4a032-a8e4-40b2-81e4-7dd34d8619e2
		summarizeBy: sum
		sourceColumn: FiscalYearStartYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: e9418ee0-3afd-4ee1-a916-31ba41fbb3b6
		summarizeBy: sum
		sourceColumn: FiscalMonthNumber

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 0e87c7a1-aad0-47b2-9a23-bd45a6798a7d
		summarizeBy: sum
		sourceColumn: FiscalQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FiscalMonthIndex
		dataType: int64
		formatString: 0
		lineageTag: e50ac018-bddc-45b7-9da8-e807c90ecff6
		summarizeBy: sum
		sourceColumn: FiscalMonthIndex

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterIndex
		dataType: int64
		formatString: 0
		lineageTag: bb25b3c1-9c01-4755-be5d-407ece724eb6
		summarizeBy: sum
		sourceColumn: FiscalQuarterIndex

		annotation SummarizationSetBy = Automatic

	column FiscalMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: 6a609d2d-c630-402e-9e2f-3d4b00dbceb0
		summarizeBy: sum
		sourceColumn: FiscalMonthOffset

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 066b0185-6db5-45bb-94c8-dc07239c875c
		summarizeBy: sum
		sourceColumn: FiscalQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FiscalQuarterName
		dataType: string
		lineageTag: 5c813765-8bbe-4f6d-81d1-157d67b7e1c9
		summarizeBy: none
		sourceColumn: FiscalQuarterName

		annotation SummarizationSetBy = Automatic

	column FiscalYearBin
		dataType: string
		lineageTag: a553281e-cb5d-4f95-9369-4ac160177bd5
		summarizeBy: none
		sourceColumn: FiscalYearBin

		annotation SummarizationSetBy = Automatic

	column FiscalYearStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: fde42b8d-2d39-4d89-a60b-b8e26597b6cb
		summarizeBy: none
		sourceColumn: FiscalYearStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalYearEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6c0ac05b-df6e-476f-b64b-38845bb3366c
		summarizeBy: none
		sourceColumn: FiscalYearEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalQuarterStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 187b3d91-d671-4bca-b1c1-8cce64fb46f1
		summarizeBy: none
		sourceColumn: FiscalQuarterStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FiscalQuarterEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c3f7a1e9-9a84-4da0-9859-78ba68d864a5
		summarizeBy: none
		sourceColumn: FiscalQuarterEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsFiscalYearStart
		dataType: int64
		formatString: 0
		lineageTag: 02194d73-cdb5-4a54-9c02-240fb362ec27
		summarizeBy: sum
		sourceColumn: IsFiscalYearStart

		annotation SummarizationSetBy = Automatic

	column IsFiscalYearEnd
		dataType: int64
		formatString: 0
		lineageTag: 79d3e234-ba02-4703-b08e-dd4fc2ca14a1
		summarizeBy: sum
		sourceColumn: IsFiscalYearEnd

		annotation SummarizationSetBy = Automatic

	column IsFiscalQuarterStart
		dataType: int64
		formatString: 0
		lineageTag: c752ed07-9e3d-461f-83e8-2c576beaf02c
		summarizeBy: sum
		sourceColumn: IsFiscalQuarterStart

		annotation SummarizationSetBy = Automatic

	column IsFiscalQuarterEnd
		dataType: int64
		formatString: 0
		lineageTag: 55edba9a-480c-4282-b023-c8b9aba493a0
		summarizeBy: sum
		sourceColumn: IsFiscalQuarterEnd

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: 9ffbb6c1-9e9c-47c5-a52e-837588614ec0
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalYearLabel
		dataType: string
		lineageTag: 1b5124d2-ffec-481e-829a-7e6ab2188607
		summarizeBy: none
		sourceColumn: FiscalYearLabel

		annotation SummarizationSetBy = Automatic

	column FiscalSystem
		dataType: string
		lineageTag: 0e2363f7-5db8-499e-b03f-5997cb88ff5b
		summarizeBy: none
		sourceColumn: FiscalSystem

		annotation SummarizationSetBy = Automatic

	column WeeklyFiscalSystem
		dataType: string
		lineageTag: dac5ab7b-2416-453a-a974-96167d108b4c
		summarizeBy: none
		sourceColumn: WeeklyFiscalSystem

		annotation SummarizationSetBy = Automatic

	column FWYearNumber
		dataType: int64
		formatString: 0
		lineageTag: ac5585c0-c927-4dea-8c38-0c9485bc3dae
		summarizeBy: sum
		sourceColumn: FWYearNumber

		annotation SummarizationSetBy = Automatic

	column FWYearLabel
		dataType: string
		lineageTag: f45c504d-4544-48cf-85ce-be3682892b08
		summarizeBy: none
		sourceColumn: FWYearLabel

		annotation SummarizationSetBy = Automatic

	column FWQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 174f0153-ea85-47fa-a5eb-2351cdd66f1d
		summarizeBy: sum
		sourceColumn: FWQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWQuarterLabel
		dataType: string
		lineageTag: dddcf07b-877f-4fb1-9cdb-a9e76f254d03
		summarizeBy: none
		sourceColumn: FWQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FWYearQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 32a054a8-8e5d-4563-911e-82fa2307bfb3
		summarizeBy: sum
		sourceColumn: FWYearQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWYearQuarterOffset
		dataType: int64
		formatString: 0
		lineageTag: 234229f8-8636-4260-a7c5-9c678e7088b5
		summarizeBy: sum
		sourceColumn: FWYearQuarterOffset

		annotation SummarizationSetBy = Automatic

	column FWMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 67882df4-719c-4808-adb1-5735dcbfb311
		summarizeBy: sum
		sourceColumn: FWMonthNumber

		annotation SummarizationSetBy = Automatic

	column FWMonthLabel
		dataType: string
		lineageTag: 329d10a2-14d5-4b05-8408-88ab36cbc729
		summarizeBy: none
		sourceColumn: FWMonthLabel

		annotation SummarizationSetBy = Automatic

	column FWYearMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: d3391a38-ede2-46d8-b225-e4acfa5021a0
		summarizeBy: sum
		sourceColumn: FWYearMonthNumber

		annotation SummarizationSetBy = Automatic

	column FWYearMonthOffset
		dataType: int64
		formatString: 0
		lineageTag: 54f6df6d-fd42-4a9b-ba86-0d4cc270d125
		summarizeBy: sum
		sourceColumn: FWYearMonthOffset

		annotation SummarizationSetBy = Automatic

	column FWWeekNumber
		dataType: int64
		formatString: 0
		lineageTag: 9f06f9ce-fdb2-4795-8c81-9d5efa0f0b60
		summarizeBy: sum
		sourceColumn: FWWeekNumber

		annotation SummarizationSetBy = Automatic

	column FWWeekLabel
		dataType: string
		lineageTag: d411b69e-0e5c-41b8-bcc4-505b04232200
		summarizeBy: none
		sourceColumn: FWWeekLabel

		annotation SummarizationSetBy = Automatic

	column FWYearWeekNumber
		dataType: int64
		formatString: 0
		lineageTag: c13a8c82-710f-40f9-b0a9-f7ee1744e340
		summarizeBy: sum
		sourceColumn: FWYearWeekNumber

		annotation SummarizationSetBy = Automatic

	column FWYearWeekOffset
		dataType: int64
		formatString: 0
		lineageTag: 63f1acee-a65f-48db-9b89-a93e7367a200
		summarizeBy: sum
		sourceColumn: FWYearWeekOffset

		annotation SummarizationSetBy = Automatic

	column FWPeriodNumber
		dataType: int64
		formatString: 0
		lineageTag: 91d42c94-bd9d-4d84-913a-74c89cbbdb3b
		summarizeBy: sum
		sourceColumn: FWPeriodNumber

		annotation SummarizationSetBy = Automatic

	column FWPeriodLabel
		dataType: string
		lineageTag: 04b82912-20f5-402b-9f9a-a8c5dce03818
		summarizeBy: none
		sourceColumn: FWPeriodLabel

		annotation SummarizationSetBy = Automatic

	column FWStartOfYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: 500ba086-124a-48e7-a1df-8e95d1b68800
		summarizeBy: none
		sourceColumn: FWStartOfYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfYear
		dataType: dateTime
		formatString: Long Date
		lineageTag: a0edab35-6d1a-4080-a3ca-29532480d137
		summarizeBy: none
		sourceColumn: FWEndOfYear

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWStartOfQuarter
		dataType: dateTime
		formatString: Long Date
		lineageTag: 282590b7-3719-4897-87ef-618edc448440
		summarizeBy: none
		sourceColumn: FWStartOfQuarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfQuarter
		dataType: dateTime
		formatString: Long Date
		lineageTag: ae66e001-72af-4664-bead-ab63903f42f9
		summarizeBy: none
		sourceColumn: FWEndOfQuarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWStartOfMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6e421af6-ccdd-4e6b-adf2-b803582f8aa5
		summarizeBy: none
		sourceColumn: FWStartOfMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfMonth
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4a02ffeb-29c0-48c5-94e1-bc97a37ea079
		summarizeBy: none
		sourceColumn: FWEndOfMonth

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWStartOfWeek
		dataType: dateTime
		formatString: Long Date
		lineageTag: a46d90c1-f284-416b-ab3d-ab3a2ad14af0
		summarizeBy: none
		sourceColumn: FWStartOfWeek

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FWEndOfWeek
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1a59f541-5533-4af1-aa8c-48c94626df07
		summarizeBy: none
		sourceColumn: FWEndOfWeek

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekDayNumber
		dataType: int64
		formatString: 0
		lineageTag: 2e5adc0f-033b-4c4f-bc5d-17e29801b204
		summarizeBy: sum
		sourceColumn: WeekDayNumber

		annotation SummarizationSetBy = Automatic

	column WeekDayNameShort
		dataType: string
		lineageTag: 4b80241e-a4ba-46ef-bfa6-42f1904393a4
		summarizeBy: none
		sourceColumn: WeekDayNameShort

		annotation SummarizationSetBy = Automatic

	column FWDayOfYearNumber
		dataType: int64
		formatString: 0
		lineageTag: d8e760f5-ac87-4040-98ec-fe2c5b14c727
		summarizeBy: sum
		sourceColumn: FWDayOfYearNumber

		annotation SummarizationSetBy = Automatic

	column FWDayOfQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 7d6e2862-c40b-43f7-b8a5-88af6207d655
		summarizeBy: sum
		sourceColumn: FWDayOfQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWDayOfMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 89b4be62-c9ec-4c81-adfc-ab4f39cc8ed1
		summarizeBy: sum
		sourceColumn: FWDayOfMonthNumber

		annotation SummarizationSetBy = Automatic

	column IsWorkingDay
		dataType: int64
		formatString: 0
		lineageTag: 280f980f-6477-492a-89a4-bafc32811ab7
		summarizeBy: sum
		sourceColumn: IsWorkingDay

		annotation SummarizationSetBy = Automatic

	column DayType
		dataType: string
		lineageTag: 7969e12f-5c94-4308-b926-8fddd7939580
		summarizeBy: none
		sourceColumn: DayType

		annotation SummarizationSetBy = Automatic

	column FWWeekInQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 9d4c1a33-2cab-4703-8b48-edab1b5b7421
		summarizeBy: sum
		sourceColumn: FWWeekInQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FWYearMonthLabel
		dataType: string
		lineageTag: ff52c7a6-c216-4c36-a14c-4deb3cc99550
		summarizeBy: none
		sourceColumn: FWYearMonthLabel

		annotation SummarizationSetBy = Automatic

	partition Dates = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "dates" ),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type date}, {"DateKey", Int64.Type}, {"SequentialDayIndex", Int64.Type}, {"Year", Int64.Type}, {"Quarter", Int64.Type}, {"QuarterStartDate", type date}, {"QuarterEndDate", type date}, {"QuarterYear", type text}, {"Month", Int64.Type}, {"MonthName", type text}, {"MonthShort", type text}, {"MonthStartDate", type date}, {"MonthEndDate", type date}, {"MonthYear", type date}, {"MonthYearNumber", Int64.Type}, {"YearQuarterKey", Int64.Type}, {"CalendarMonthIndex", Int64.Type}, {"CalendarQuarterIndex", Int64.Type}, {"WeekOfMonth", Int64.Type}, {"Day", Int64.Type}, {"DayName", type text}, {"DayShort", type text}, {"DayOfYear", Int64.Type}, {"DayOfWeek", Int64.Type}, {"IsWeekend", Int64.Type}, {"IsBusinessDay", Int64.Type}, {"NextBusinessDay", type date}, {"PreviousBusinessDay", type date}, {"IsYearStart", Int64.Type}, {"IsYearEnd", Int64.Type}, {"IsQuarterStart", Int64.Type}, {"IsQuarterEnd", Int64.Type}, {"IsMonthStart", Int64.Type}, {"IsMonthEnd", Int64.Type}, {"IsToday", Int64.Type}, {"IsCurrentYear", Int64.Type}, {"IsCurrentMonth", Int64.Type}, {"IsCurrentQuarter", Int64.Type}, {"CurrentDayOffset", Int64.Type}, {"YearOffset", Int64.Type}, {"CalendarMonthOffset", Int64.Type}, {"CalendarQuarterOffset", Int64.Type}, {"FiscalYearStartYear", Int64.Type}, {"FiscalMonthNumber", Int64.Type}, {"FiscalQuarterNumber", Int64.Type}, {"FiscalMonthIndex", Int64.Type}, {"FiscalQuarterIndex", Int64.Type}, {"FiscalMonthOffset", Int64.Type}, {"FiscalQuarterOffset", Int64.Type}, {"FiscalQuarterName", type text}, {"FiscalYearBin", type text}, {"FiscalYearStartDate", type date}, {"FiscalYearEndDate", type date}, {"FiscalQuarterStartDate", type date}, {"FiscalQuarterEndDate", type date}, {"IsFiscalYearStart", Int64.Type}, {"IsFiscalYearEnd", Int64.Type}, {"IsFiscalQuarterStart", Int64.Type}, {"IsFiscalQuarterEnd", Int64.Type}, {"FiscalYear", Int64.Type}, {"FiscalYearLabel", type text}, {"FiscalSystem", type text}, {"WeeklyFiscalSystem", type text}, {"FWYearNumber", Int64.Type}, {"FWYearLabel", type text}, {"FWQuarterNumber", Int64.Type}, {"FWQuarterLabel", type text}, {"FWYearQuarterNumber", Int64.Type}, {"FWYearQuarterOffset", Int64.Type}, {"FWMonthNumber", Int64.Type}, {"FWMonthLabel", type text}, {"FWYearMonthNumber", Int64.Type}, {"FWYearMonthOffset", Int64.Type}, {"FWWeekNumber", Int64.Type}, {"FWWeekLabel", type text}, {"FWYearWeekNumber", Int64.Type}, {"FWYearWeekOffset", Int64.Type}, {"FWPeriodNumber", Int64.Type}, {"FWPeriodLabel", type text}, {"FWStartOfYear", type date}, {"FWEndOfYear", type date}, {"FWStartOfQuarter", type date}, {"FWEndOfQuarter", type date}, {"FWStartOfMonth", type date}, {"FWEndOfMonth", type date}, {"FWStartOfWeek", type date}, {"FWEndOfWeek", type date}, {"WeekDayNumber", Int64.Type}, {"WeekDayNameShort", type text}, {"FWDayOfYearNumber", Int64.Type}, {"FWDayOfQuarterNumber", Int64.Type}, {"FWDayOfMonthNumber", Int64.Type}, {"IsWorkingDay", Int64.Type}, {"DayType", type text}, {"FWWeekInQuarterNumber", Int64.Type}, {"FWYearMonthLabel", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

