table EmployeeStoreAssignment
	lineageTag: 1454de38-631b-4308-9560-8def0bdf1a09

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 97d1104d-2a2b-43c7-a85f-e8d8104f9675
		summarizeBy: count
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 0e4a66d3-9e7b-4380-a1c1-8f722ca3bc8e
		summarizeBy: count
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c7658cc4-37e6-41bf-a885-fdf2856452a6
		summarizeBy: none
		sourceColumn: StartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column EndDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d7748d6a-78a9-432b-80f8-27b2a4903278
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column FTE
		dataType: double
		lineageTag: f99cdc08-1a77-4981-af24-6cce8198f111
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RoleAtStore
		dataType: string
		lineageTag: cf067b92-f1d2-451c-b8cf-153168aa6835
		summarizeBy: none
		sourceColumn: RoleAtStore

		annotation SummarizationSetBy = Automatic

	column IsPrimary
		dataType: int64
		formatString: 0
		lineageTag: 2dba3339-4950-4115-ad05-1509751bd9dd
		summarizeBy: sum
		sourceColumn: IsPrimary

		annotation SummarizationSetBy = Automatic

	column AssignmentSequence
		dataType: int64
		formatString: 0
		lineageTag: 84c9528d-96ad-4b64-af58-5be3b02047f4
		summarizeBy: sum
		sourceColumn: AssignmentSequence

		annotation SummarizationSetBy = Automatic

	partition EmployeeStoreAssignment = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "employee_store_assignments" ),
				    ChangedType = Table.TransformColumnTypes (
				        Source,
				        {
				            { "EmployeeKey", Int64.Type },
				            { "StoreKey", Int64.Type },
				            { "StartDate", type date },
				            { "EndDate", type date },
				            { "FTE", type number },
				            { "RoleAtStore", type text },
				            { "IsPrimary", Int64.Type },
				            { "AssignmentSequence", Int64.Type }
				        }
				    )
				in
				    ChangedType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

