table ExchangeRateMonthly
	lineageTag: 78696f82-e6c3-471e-852f-386ebe9782d7

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d682c440-aae8-41b1-a8dc-06bda55748a0
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FromCurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 90e24fed-b5b2-48d0-9119-d1be89cf0f8c
		summarizeBy: count
		sourceColumn: FromCurrencyKey

		annotation SummarizationSetBy = Automatic

	column ToCurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 1e65db27-ae40-4dad-bb25-866491564bd0
		summarizeBy: count
		sourceColumn: ToCurrencyKey

		annotation SummarizationSetBy = Automatic

	column FromCurrency
		dataType: string
		lineageTag: ebb84b4e-d71c-480a-9e90-0bc296814228
		summarizeBy: none
		sourceColumn: FromCurrency

		annotation SummarizationSetBy = Automatic

	column ToCurrency
		dataType: string
		lineageTag: 0eb6970f-81ee-4ae6-be8d-09132ac29ad6
		summarizeBy: none
		sourceColumn: ToCurrency

		annotation SummarizationSetBy = Automatic

	column AvgRate
		dataType: double
		lineageTag: d02bd7bf-92cd-488c-9d70-81e3f818be67
		summarizeBy: sum
		sourceColumn: AvgRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MinRate
		dataType: double
		lineageTag: 05c16e63-7c9b-4502-8e3f-f2361b0cb8cb
		summarizeBy: sum
		sourceColumn: MinRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MaxRate
		dataType: double
		lineageTag: b11a11c9-a3bf-4aed-aac0-d378792ff743
		summarizeBy: sum
		sourceColumn: MaxRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EndOfMonthRate
		dataType: double
		lineageTag: e414a210-3107-4eea-818e-dc6fb59735d5
		summarizeBy: sum
		sourceColumn: EndOfMonthRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ExchangeRateMonthly = m
		mode: import
		queryGroup: Fact\ExchangeRates
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "exchange_rates_monthly" ),
				    ChangedType = Table.TransformColumnTypes(Source,{{"Date", type date}, {"FromCurrencyKey", Int64.Type}, {"ToCurrencyKey", Int64.Type}, {"FromCurrency", type text}, {"ToCurrency", type text}, {"AvgRate", type number}, {"MinRate", type number}, {"MaxRate", type number}, {"EndOfMonthRate", type number}})
				in
				    ChangedType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

