table Products
	lineageTag: a736d030-7050-4b89-afb0-103296247af9

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 817fb5b9-efba-4622-9733-06c52a3785e4
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductCode
		dataType: int64
		formatString: 0
		lineageTag: 361f0e4b-eb23-4937-8dac-22a201b28459
		summarizeBy: count
		sourceColumn: ProductCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 22321e1c-f522-4b5f-874e-aa5d32b76c35
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ProductDescription
		dataType: string
		lineageTag: 15e4db0b-ef90-4c66-88a9-8b3b8b5e6396
		summarizeBy: none
		sourceColumn: ProductDescription

		annotation SummarizationSetBy = Automatic

	column SubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 169bba0b-83a5-49c2-ae55-f76e8d03183f
		summarizeBy: count
		sourceColumn: SubcategoryKey

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: a2dc35fb-6ee5-4ff5-9adf-abc288b1c3ef
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Class
		dataType: string
		lineageTag: 589d9b5a-c66d-4b43-80bd-0538d5efe4a7
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 6ee81513-8370-473a-8cca-279477f735db
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column StockTypeCode
		dataType: int64
		formatString: 0
		lineageTag: 29179efc-8bbc-464f-a2ec-9dc6e80bc4a8
		summarizeBy: count
		sourceColumn: StockTypeCode

		annotation SummarizationSetBy = Automatic

	column StockType
		dataType: string
		lineageTag: 74663ff5-bf7e-41b9-b2de-5187e17f5f63
		summarizeBy: none
		sourceColumn: StockType

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: decimal
		formatString: #,0.00
		lineageTag: 55417800-0963-4dcf-bbb2-b6a61d0f428a
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: #,0.00
		lineageTag: 11e753c5-0f96-43ea-83b7-a269d2c1a0d6
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column BaseProductKey
		dataType: int64
		formatString: 0
		lineageTag: e1219f43-3c77-47eb-8654-8da6b4a5df26
		summarizeBy: count
		sourceColumn: BaseProductKey

		annotation SummarizationSetBy = Automatic

	column VariantIndex
		dataType: int64
		formatString: 0
		lineageTag: 849c6ce3-9802-4902-a69f-56f08d095ce9
		summarizeBy: sum
		sourceColumn: VariantIndex

		annotation SummarizationSetBy = Automatic

	column IsActiveInSales
		dataType: int64
		formatString: 0
		lineageTag: 8c492ffd-f8ae-4dda-86fe-9a9c21684a60
		summarizeBy: sum
		sourceColumn: IsActiveInSales

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = FxReadCSVFile ( "dimensions", "products" ),
				    ChangedType = Table.TransformColumnTypes (
				        Source,
				        {
				            { "ProductKey", Int64.Type },
				            { "ProductCode", Int64.Type },
				            { "ProductName", type text },
				            { "ProductDescription", type text },
				            { "SubcategoryKey", Int64.Type },
				            { "Brand", type text },
				            { "Class", type text },
				            { "Color", type text },
				            { "StockTypeCode", Int64.Type },
				            { "StockType", type text },
				            { "UnitCost", Currency.Type },
				            { "UnitPrice", Currency.Type },
				            { "BaseProductKey", Int64.Type },
				            { "VariantIndex", Int64.Type },
				            { "IsActiveInSales", Int64.Type }
				        }
				    )
				in
				    ChangedType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

