table SalesReturns
	lineageTag: e5942e12-813c-4803-97fb-879b388a5987

	column SalesOrderNumber
		dataType: int64
		formatString: 0
		lineageTag: 6f44264e-b30f-45fd-bc01-cb9ec8c8f392
		summarizeBy: sum
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 00d34491-6def-4c63-8e04-3d7a1e728452
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column ReturnDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9451fe9a-f083-4190-8d6c-958bc37bcc4f
		summarizeBy: none
		sourceColumn: ReturnDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ReturnReasonKey
		dataType: int64
		formatString: 0
		lineageTag: 319bbbca-fc01-4988-aaf9-cb327adf50c7
		summarizeBy: count
		sourceColumn: ReturnReasonKey

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: d0a276e4-0664-4bf4-90f8-18f4b84bbb33
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	column ReturnNetPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 960bbb07-8532-45cc-a0be-e6c2de7189c0
		summarizeBy: sum
		sourceColumn: ReturnNetPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ReturnEventKey
		dataType: int64
		formatString: 0
		lineageTag: 8692fdd7-113c-4d32-8ac6-601e19260d9a
		summarizeBy: count
		sourceColumn: ReturnEventKey

		annotation SummarizationSetBy = Automatic

	partition SalesReturns = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = Folder.Files ( ContosoFolder & "\facts\sales_return" ),
				    RemoveCols = Table.SelectColumns ( Source, { "Content" } ),
				    RemoveHidden = Table.SelectRows ( RemoveCols, each [Attributes]?[Hidden]? <> true ),
				    InvokeCustom = Table.AddColumn (
				        RemoveHidden,
				        "Transform File",
				        each Transform_SalesReturns_File ( [Content] )
				    ),
				    RemoveOtherCol = Table.SelectColumns ( InvokeCustom, { "Transform File" } ),
				    CombineTables = Table.ExpandTableColumn (
				        RemoveOtherCol,
				        "Transform File",
				        Table.ColumnNames ( Transform_SalesReturns_File ( Sample_File_SalesReturns ) )
				    ),
				    ChangeType = Table.TransformColumnTypes (
				        CombineTables,
				        {
				            { "SalesOrderNumber", Int64.Type },
				            { "SalesOrderLineNumber", Int64.Type },
				            { "ReturnDate", type date },
				            { "ReturnReasonKey", Int64.Type },
				            { "ReturnQuantity", Int64.Type },
				            { "ReturnNetPrice", Currency.Type },
				            { "ReturnEventKey", Int64.Type }
				        }
				    )
				in
				    ChangeType

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

