table SalesOrderHeader
	isHidden
	lineageTag: a6858967-9b2f-4631-b1db-1fc3279814ea

	column SalesOrderNumber
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f54cd52d-191e-41c3-9c06-c3c4c0b2941a
		summarizeBy: sum
		sourceColumn: SalesOrderNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e494926b-c112-4d65-a2f5-d01b8272d2e0
		summarizeBy: count
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: cfc3783a-99e1-4910-a1f6-077df3c58ad9
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsOrderDelayed
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7d1250a8-8b99-4926-a95c-848b1126a628
		summarizeBy: sum
		sourceColumn: IsOrderDelayed

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 98c12d4c-86d6-41fb-bb4c-ce3fe3ce58a4
		summarizeBy: count
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column SalesPersonEmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 0d014db4-23ef-41a8-8c60-2808ee6f5e3a
		summarizeBy: count
		sourceColumn: SalesPersonEmployeeKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: 6780fdb5-040c-4943-be69-38d879da1f07
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 00eb9a70-0ba3-468e-9569-2bc7d9c18b67
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column SalesChannelKey
		dataType: int64
		formatString: 0
		lineageTag: 1e5cec2c-633d-40c2-8b4e-c787cc16de2a
		summarizeBy: count
		sourceColumn: SalesChannelKey

		annotation SummarizationSetBy = Automatic

	column TimeKey
		dataType: int64
		formatString: 0
		lineageTag: 597de895-c94c-4af2-90a6-cc70f49c9ec9
		summarizeBy: count
		sourceColumn: TimeKey

		annotation SummarizationSetBy = Automatic

	partition SalesOrderHeader = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = Folder.Files ( ContosoFolder & "\facts\sales_order_header" ),
				    FilterHidden = Table.SelectRows ( Source, each [Attributes]?[Hidden]? <> true ),
				    InvokeCustomFunction = Table.AddColumn (
				        FilterHidden,
				        "Transform File",
				        each Transform_SOH_File ( [Content] )
				    ),
				    RenameCols = Table.RenameColumns ( InvokeCustomFunction, { "Name", "Source.Name" } ),
				    RemoveOtherCols = Table.SelectColumns ( RenameCols, { "Transform File" } ),
				    ExpandTable = Table.ExpandTableColumn (
				        RemoveOtherCols,
				        "Transform File",
				        Table.ColumnNames ( Transform_SOH_File ( Sample_File_SOH ) )
				    ),
				    ChangedType = Table.TransformColumnTypes (
				        ExpandTable,
				        {
				            { "SalesOrderNumber", Int64.Type },
				            { "CustomerKey", Int64.Type },
				            { "StoreKey", Int64.Type },
				            { "SalesPersonEmployeeKey", Int64.Type },
				            { "SalesChannelKey", Int64.Type },
				            { "OrderDate", type date },
				            { "TimeKey", Int64.Type },
				            { "IsOrderDelayed", Int64.Type },
				            { "PromotionKey", Int64.Type },
				            { "CurrencyKey", Int64.Type }
				        }
				    )
				in
				    ChangedType

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

