table Sales
	lineageTag: 98d27fd9-d067-4f71-8701-62e4cf08a2f5

	column SalesOrderNumber
		dataType: int64
		formatString: 0
		lineageTag: 65df8146-1199-43ff-a8b3-0709583ed02a
		summarizeBy: sum
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: e69c2d84-eba5-46ff-ac4e-23ee9db30392
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 86e1d5dc-6574-4429-88c1-414f48a548f2
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 24f9e5f0-13db-40d3-ab6b-4794cfafde68
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: 812a2932-1aa8-431a-8894-ec520dc15605
		summarizeBy: count
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column SalesPersonEmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 4e4ed5a1-638c-4273-9d23-4cd859a559af
		summarizeBy: count
		sourceColumn: SalesPersonEmployeeKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: 6b940f89-6bd9-4b5c-96cb-e4e98739128e
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 52788aad-0ac0-4935-8ffe-bb7c686716f3
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column SalesChannelKey
		dataType: int64
		formatString: 0
		lineageTag: 799a98da-8823-4ae7-a0b2-5a65e8c2257f
		summarizeBy: count
		sourceColumn: SalesChannelKey

		annotation SummarizationSetBy = Automatic

	column TimeKey
		dataType: int64
		formatString: 0
		lineageTag: f2fe7646-d9af-4b9a-a535-72892f20c5f0
		summarizeBy: count
		sourceColumn: TimeKey

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d4d058a-589e-4eb0-af7e-3095bc188d20
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a38acfb8-3477-4011-8824-31cb8169d7cf
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DeliveryDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a9e8ffd5-b406-432b-a8c4-317823f3dd28
		summarizeBy: none
		sourceColumn: DeliveryDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 1bd55201-9bab-468d-a774-971c9e843e4d
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column NetPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: be0422ab-91b7-418b-8e7f-bbcc79b9d070
		summarizeBy: sum
		sourceColumn: NetPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column UnitCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ae56ded0-cde8-4abd-8785-59e0bd7767b1
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: cd609fcf-96d2-45ee-8940-cef6d2bcceec
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column DiscountAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4ab04d2b-cd14-4479-a92b-f9aaa32ea086
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column DeliveryStatus
		dataType: string
		lineageTag: 06a2f63f-3a80-4ba3-bbb8-41da5cf7c447
		summarizeBy: none
		sourceColumn: DeliveryStatus

		annotation SummarizationSetBy = Automatic

	column IsOrderDelayed
		dataType: int64
		formatString: 0
		lineageTag: 3ef95355-4c27-4e0e-b889-715c3442b2f3
		summarizeBy: sum
		sourceColumn: IsOrderDelayed

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		queryGroup: Fact
		source =
				let
				    Source = Folder.Files ( ContosoFolder & "\facts\sales" ),
				    RemoveCols = Table.SelectColumns ( Source, { "Content" } ),
				    RemoveHidden = Table.SelectRows ( RemoveCols, each [Attributes]?[Hidden]? <> true ),
				    InvokeCustom = Table.AddColumn (
				        RemoveHidden,
				        "Transform File",
				        each Transform_Sales_File ( [Content] )
				    ),
				    RemoveOtherCol = Table.SelectColumns ( InvokeCustom, { "Transform File" } ),
				    CombineTables = Table.ExpandTableColumn (
				        RemoveOtherCol,
				        "Transform File",
				        Table.ColumnNames ( Transform_Sales_File ( Sample_File_Sales ) )
				    ),
				    DataTypes = {
				        { "SalesOrderNumber", Int64.Type },
				        { "SalesOrderLineNumber", Int64.Type },
				        { "CustomerKey", Int64.Type },
				        { "ProductKey", Int64.Type },
				        { "StoreKey", Int64.Type },
				        { "PromotionKey", Int64.Type },
				        { "CurrencyKey", Int64.Type },
				        { "OrderDate", type date },
				        { "DueDate", type date },
				        { "DeliveryDate", type date },
				        { "Quantity", Int64.Type },
				        { "NetPrice", Currency.Type },
				        { "UnitCost", Currency.Type },
				        { "UnitPrice", Currency.Type },
				        { "DiscountAmount", Currency.Type },
				        { "DeliveryStatus", type text },
				        { "IsOrderDelayed", Int64.Type },
				        { "SalesPersonEmployeeKey", Int64.Type },
				        { "SalesChannelKey", Int64.Type },
				        { "TimeKey", Int64.Type }
				    },
				    CheckNamesForTypes =
				        if List.ContainsAny (
				            Table.ColumnNames ( CombineTables ),
				            { "SalesOrderNumber", "SalesOrderLineNumber" }
				        )
				        then
				            DataTypes
				        else
				            List.RemoveFirstN ( DataTypes, 2 ),
				    ChangeTypes = Table.TransformColumnTypes ( CombineTables, CheckNamesForTypes )
				in
				    ChangeTypes

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

